### ISSUE TITLE
More detail and examples needed here

### ISSUE THREAD

**Issue by jjpepper** [NuGet/docs.microsoft.com-nuget#1013]
It would be great to have an example .nuspec file here that was created for a C++ project, perhaps a linux one and a windows one.  We're currently trying to build a single nuget package that contains our unmanaged dependencies for both linux and windows so that the same package can be used in development and deployment.  It's taking a long time to get this working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae24ac6-e495-0b9f-9fc9-eef609e2492b
* Version Independent ID: 86486a38-2180-49aa-68ac-36f8dd0629e1
* Content: [Creating Native NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/native-packages)
* Content Source: [docs/create-packages/Native-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Native-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by jjpepper** [comment]
Note that we are trying to create a native package that can be consumed by a C# application that P/Invokes into the libraries in the native package.  So we expect to see the native ".so" files (or ".dll" files) end up in the target directory alongside the managed DLLs of our application.  This isn't happening.

Here's a sample of our .nuspec file. 

```<?xml version="1.0"?>
<package>
  <metadata>
    <id>MyNativePackage</id>
    <authors>My Company</authors>
    <version>1.0</version>
    <owners>BlahBlah</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>native files for my package built by my CI tool</description>
    <releaseNotes></releaseNotes>
    <copyright>Copyright 2018</copyright>
    <tags>native</tags>
<!--
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="?what here?" targetFramework="native"/>
    </frameworkAssemblies>
-->
    <dependencies>
      <group targetFramework="native"/>
    </dependencies>
  </metadata>
  <files>
    <file src="*.so" target="build\native"/>
 <!--
    also tried adding files under target "build\netcoreapp2.0" to no avail
    <file src="libA.so" target="build\libA.so"/>
    <file src="libB.so" target="build\libB.so"/>
    <file src="libC.so" target="build\libC.so"/> 
-->
  </files>
</package>```

**Comment by Mizux** [comment]
@jjpepper did you manage to get a working thing ?
I'm currently try to do the same and experiment in https://github.com/Mizux/dotnet without any success...

**Comment by jjpepper** [comment]
@Mizux, we got it working using a packageName.targets file.

**Comment by karann-msft** [comment]
The work around this being tracked here - https://github.com/NuGet/docs.microsoft.com-nuget/issues/238

**Comment by Mizux** [comment]
@jjpepper Thanks !

On my side I manage to do it like this (only using a bunch of `.csproj`) :
1. On each targeted host
    - create a `runtime.{rid}.Foo.csproj` with:
    - `AssemblyName` must be `Mizux.Foo.dll` i.e. all {rid} projects **must** generate an assembly with the **same** name (i.e. no {rid} in the name)
   ```xml
   <RuntimeIdentifier>{rid}</RuntimeIdentifier>
   <AssemblyName>Mizux.Foo</AssemblyName>
   <PackageId>runtime.{rid}.Mizux.Foo</PackageId>
   ```
   - specify the output target folder for having the assembly in `runtimes/{rid}/lib/{framework}` in the nupkg
   ```xml
   <BuildOutputTargetFolder Condition="'$(RuntimeIdentifier)' != ''">runtimes/$(RuntimeIdentifier)/lib</BuildOutputTargetFolder>
   ```
   - Generate the Reference Assembly (but don't include it in the nupkg !) using:
   ```xml
   <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
   ```
   - Finally `dotnet build path/runtime.{rid}.Foo.csproj`
   - Then `dotnet pack path/runtime.{rid}.Foo.csproj` to generate
   **`runtime.{rid}.Mizux.Foo.nupkg`**
2. On one host used to build one runtime package previously:
   - copy each runtime package(s) of 1) in a directory (let's say `package`)
   - create a `Foo.csproj` with:
   - add dependency on each package(s) if availabe
   ```xml
   <PropertyGroup>
     <RestoreSources>package;$(RestoreSources)</RestoreSources>
   </PropertyGroup>
   <ItemGroup Condition="Exists('package/runtime.linux-x64.Mizux.Foo.1.0.0.nupkg')">
     <PackageReference Include="runtime.linux-x64.Mizux.Foo" Version="1.0.0" />
   </ItemGroup>
   ... //same for each {rid}
   ```
   - add a runtime.json containing:
   ```xml
   {
    "runtimes": {
      "linux-x64": {
        "Mizux.Foo": {
          "runtime.linux-x64.Mizux.Foo": "1.0.0"
       }
     },
   ```
   to the Foo.csproj
   ```xml
   <Content Include="runtime.json">
     <PackagePath>runtime.json</PackagePath>
     <Pack>true</Pack>
     <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
   </Content>
   ```
   - make also the `Foo.csproj` copy one of the runtime RefAssembly (that's why you must create it on 
   one of the previous machine used to build one runtime package)
   ```xml
   <ItemGroup>
     <Content Include="../runtime.linux-x64.Foo/bin/$(Configuration)/$(TargetFramework)/linux-x64/ref/*.dll">
       <PackagePath>ref/$(TargetFramework)/%(Filename)%(Extension)</PackagePath>
       <Pack>true</Pack>
       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
     </Content>
   ```
   - Finnaly `dotnet pack path/Foo.csproj` to generate
   **`Mizux.Foo.nupkg`**
3. upload everything, profit

note:
- Since Foo contains refAssembly project BarApp will "see" the assembly when `PackageReference` Foo.
- You can found a graph of the process on my git repo [README.md](https://github.com/Mizux/dotnet/blob/master/README.md) (Work in Progress).

**Comment by deinok** [comment]
@Mizux This is the first extended explanation on how to pack well native binaries. I fucking love you :)
