### ISSUE TITLE
Microsoft.codeDom.Providers.DotNetCompilerPlatform.2.0.0 missing

### ISSUE THREAD

**Issue by paramkaurHartek** [NuGet/docs.microsoft.com-nuget#1070]
I have Packages.config set as package management method.  i have ensured the package is installed and is present in Packages folder. Still the build of the solution fails and states the package is missing. It is unable to find the projects props folder in net46 folder at the specific path.

Please suggest.

**Comment by zivkan** [comment]
One cause of this problem is when the folder structure changes. Packages.config projects add some msbuild targets into your csproj that look for the packages folder, and if you move the folder, you need to either edit the csproj or reinstall the packages in all packages.config projects. I beleive if you were using PackageReference, this should not have been a problem :)

In any case, if my suggestion above doesn't help, I'd like to ask you to create an issue on the [nuget/home](https://github.com/NuGet/Home/issues) repo with enough details to reproduct the problem.
