### ISSUE TITLE
Current approach to packaging x86 and x64 assemblies

### ISSUE THREAD

**Issue by quasarea** [NuGet/docs.microsoft.com-nuget#1083]
## Details about Problem

Cannot find any documentation on how to release x86 and x64 assemblies in a single package. I 

The [supporting-multiple-target-frameworks](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks):
> If you have architecture-specific assemblies, that is, separate assemblies that target ARM, x86, and x64, you must place them in a folder named **runtimes** (...)

The [nuspec](https://docs.microsoft.com/en-us/nuget/reference/nuspec) reference does not even once mention **runtimes** location

From what I have seen after evaluation of few native packages those are stored under **build\native\$(architecture)** or **build\native\bin\$(architecture)** and consumption is supported by .targets

The [nuspec](https://docs.microsoft.com/en-us/nuget/reference/nuspec) reference mentions **native** location next to **build** not inside it, but this is not supported by nuget package explorer 

My current gut feeling is that I should go with **build\native\x64** and **build\native\x86** but it would be great if I could support it with something more than the gut

Thanks
J

ID: f1482e18-5f1f-3a8a-3321-66af52879ec5
Version Independent ID: d70bd2f5-c04b-9207-62a0-4ecb6e8e5ca6
Content: Multi-targeting for NuGet Packages
Content Source: docs/create-packages/Supporting-Multiple-Target-Frameworks.md

**Comment by StingyJack** [comment]
Thank you for re-asking this question. If you dont mind, I'd like to expand on it a bit and ask how to package the following...

- An x86 assembly targeting net40
- An x86 assembly targeting net452
- An x64 assembly targeting net452
- An x64 assembly targeting net472

**Comment by WebDucer** [comment]
@zivkan I also interested in a documentation about multi targeting different runtimes and architectures.

**Comment by zivkan** [comment]
Until docs are written, my suggestion is to look at how other packages that have architecture dependent files work, and copy their structure.

If you're ok with your package only working in SDK style projects, then the [libuv package](https://www.nuget.org/packages/Libuv/) is an example (basically, use the nuget `runtimes/` folder)

If you want your package to support non-SDK style ("traditional") projects, the [System.Data.SQLite.Core package](https://www.nuget.org/packages/System.Data.SQLite.Core/) is an example (you need your own msbuild props and/or targets file)

**Comment by KinsonDigital** [comment]
I am personally having issues with this.  Could we re-open this issue?  I have created a **.targets** file in the **\build** folder of the package as well as a **\runtimes** folder.  I have done this with and without the **.targets** file and no matter what I do, my C# library that consumes the package always gets the packages' C# library from the packages **\lib\netcoreapp3.1** folder copied to the output folder of the consumer project.

I can and have successfully setup the **.targets** file to copy the proper **x86** and **x64** library from the **\runtimes** path to replace the incorrect architecture library in the **main output folder of the consumer project**, but  I always get warnings the the architecture is incorrect because it is looking at the library in the **global .nuget cache folder**.

Any answers on how to solve this?

Here is the issue that I opened about this.  https://github.com/NuGet/Home/issues/9272

**Comment by StingyJack** [comment]
This one is actually already open, but that doesn't mean the nuget team will actually do anything with it. 

It looks like Karan finally added it to a sprint, which would normally be a good thing, except in this case it's 1.5 years later than when I needed some kind of answers my questions.

**Comment by KinsonDigital** [comment]
That is a shame.  Due to me running into this issue, I have searched all over the internet and have been working on this issue for 2 weeks straight.  Though I have learned a lot, I have come across no real documentation of how to do this.  I also have discovered that I am definitely not the only one that has the need of multiple architectures of libraries being in the same package.

As of right now, I am being forced to have 2 separate packages.   One is a **x86** and the other is a **x64** package.  Due to this, I now have to have the consumer package have a custom setup to use either or based on the consumer packages set platform.  This is not ideal.  It has also brought to light another issue that I put into the **Visual Studio** team with the solution explorer and using conditional package references.

The need for multiple architecture libraries (native or managed) to be in the same package and the consumer of that package using it appropriately is a real need.  This will continue to become more of a need as we become more of a cross platform world as well as the NET Core ecosystem becomes more cross platform.

**Comment by zivkan** [comment]
I can't speak for everyone in my team, but of the few package authors I have talked to in the past (mostly internal to MSFT, but I used to be more active on Stack Overflow), all have been able to find a solution, usually by checking the Sqlite package and copying their technique. From a quick glance at your comment and the other issue you opened, you also found a solution that works, but it appears you're looking for a more ideal solution.

Doing a very rough (more likely to undercount than overcount) analysis of the packages on nuget.org, of the approximately 193,000 packages, under 2,500 of them appear to have x86 or x64 binaries, so little over 1%. But this includes native (C/C++) packages, not just .NET packages.

I understand your frustration at not being able to find the information you want, but I hope you can appreciate that we have finite time, so work needs to be prioritised by impact. Microsoft may be a large company, but doesn't mean we have infinite budget to hire more people. I don't have any data, but I expect most developers consume packages and never create them, so that's another thing to think about regarding the 1% of packages that might be trying to do x86/x64 asset selection. We will be working on this, and other docs issues, but this issue in particular is very complex, as you have discovered, so writing good docs is going to take non-trivial time. Since everyone appears to have been able to find solutions or workarounds, the cost-benefit ratio hasn't made it a priority yet. But we will. Docs in general are increasingly becoming a higher priority, but again docs that impact more people and are easier to write will be done before complex issues that few people will use.

My very quick comments on this topic, to the best of my current knowledge:
* To support projects that use your package with packages.config, you need to provide your own MSBuild targets file, and put your managed code in the package's `/lib/<tfm>/` folder. If the .NET SDK is overwriting the file you copied in your target with the `lib/<tfm>` assembly and you don't want that, you should modify your target to run later in the build, after the .NET SDK has copied referenced assemblies to the output folder.
* If you want to only support projects using your package with PackageReference, you don't need any MSBuild targets/props files. It's best to use `ref/` and `runtimes/`, rather than `lib/` and `runtimes/`. But this is only if you want your package to copy one of architecture binaries at compile/publish time. If you want both the x86 and x64 binaries to be copied to the project output because your managed code uses the correct one at runtime (to support AnyCPU where the runtime might not be the same architecture as compile time), NuGet's `runtimes` folder does not do what you want, and you need to keep using your own MSBuild targets file.
* runtime "inheritance" is unfortunately another very complex situation. If the project targets a `netcoreapp` TFM, then the .NET SDK will include a runtimes.json file that explains the ralationships, so that `ubuntu-x64` knows to inherit `linux-x64` and `linux` runtime assets. However, if the project's TFM is .NET Framework, no runtimes.json file is provided by default, so only the exact match RID will be used. The project can reference the Microsoft.NETCore.Platforms package, but packages should never list it as a dependency because it might have conflicts with the version that the .NET SDK uses, when the project uses a .NET Core TFM.

I don't know how to use `ref` and `runtimes` for PackageReference only and MSBuild targets for packages.config only. Both PackageReference and packages.config use the same target file naming convention, so as soon as you add it for packages.config support, PackageReference will also use it. I've never actually looked at the SQLite package myself to see if they figured it out, or if they just use their MSBuild targets file for both packages.config and PackageReference projects.

**Comment by KinsonDigital** [comment]
@zivkan Awesome information!!  Thank you for the response and it is greatly appreciated.  I can understand the position that MS is in.  I know all too well that there is only so much you can do with the time that you have, and the reasons you have given make perfect sense. 

The problem that I have is that I have both **NATIVE** and **MANAGE** libraries that are **x86** and **x64** specific.  The reason is because the native libs are SDL libraries and the manage ones interop into the native ones.

I need to have all of the native and manged libraries for both platforms in the same nuget package.  I have already figured out how to use the `/runtimes` folder properly.  I have been using the `<Content/>` elements for this part.

My issue currently is all with the manage lib itself.  The consumer project has both **x86** and **x64** platforms.  I need the consumer project to be able to use the **x86** managed library when the consumer project is set to **x86** and to use the **x64** managed library when the consumer project is set to **x64.**

What is happening is that when I build the package (using VS for testing) using the **x86** platform, it puts the **x86** managed lib into the `\lib\netcoreapp3.1` folder.  For the **x64** platform it builds the package with the **x64** managed lib into the `\lib\netcoreapp3.1` folder.  

So what I did is for the package I put the **x86** managed lib into the `\lib\x86` and the **x64** managed lib into the `\lib\64` folder.  I was hoping that the consumer project would automatically pick the right platform manage lib and copy it to the consumer projects output folder, but it doesn't.  It always copies the library from the `\lib\netcoreapp3.1` folder.  

I tried many different things such as `\lib\{tfm}\x64` and `\lib\{tfm}\x86** but none of these things worked.  Eventually the goal is to have a single nuget package that will have **DirectX** native libs for running on windows as well as **OpenGL** native libs for running on **MAC/LINUX**.  Currently I am using **SDL** as a basis to get all of this working.

Any guidance on how to solve my issue would be greatly appreciated.  If you are willing to help with this and need ANY more information and/or details, please don't hesitate to ask.

**Comment by KinsonDigital** [comment]
Quick Update:

I tried something new that I have not tried yet using the package `\ref` folder according to the documentation at **[this](https://docs.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects)** link.

It does not say anything about **architectures** but I figured that I would attempt it anyways.

Below is the structure of my nuget package.  Also all **libs** inside of the package have also been verified that they are all of the proper **architecture** and location.

Refer to this picture for package structure and libraries.

**NOTE:** The **SDL** libraries in the `\runtimes` folder are actually just text files and are not being used.  They are just there for testing out the nuget package creation that I am doing
![AssemblyExplorer](https://user-images.githubusercontent.com/4921022/76444629-97bbc480-639a-11ea-83e4-e1f6c63a7726.jpg)


The selected assembly is the one that I have been having issues with and is the assembly that the consumer project always pulls into the output folder.  This setup here is just for trying out the `\ref` folder according to the MS docs link above.

**Comment by KinsonDigital** [comment]
FYI: I don't know why the picture link is broken but if you click the link the picture does indeed show.

**Comment by zivkan** [comment]
Neither the `lib/` nor `ref/` folders know anything about architecture or runtime identifier (RID). They only support the `lib/{tfm}/assembly.dll` pattern, where {tfm} is a .NET TFM or native (and native means the package can be installed into C/C++ projects, not that these are native dependencies for your managed code).

If the problem you're trying to solve is that you're getting compiler warnings about mismatched architectures, you need to compile your managed code with AnyCPU and put that in the `ref/` folder. You could use `#if` blocks around anything that otherwise doesn't compile with AnyCPU, and you can put a [reference assembly](https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md) in the `ref/` folder to make the package smaller. The .NET BCLs do hard mode, creating a separate project and code file with just the public signatures, but no method body. See [this one for example](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/ref/System.Net.Http.cs).

Similarly if you want to support packages.config, then your managed assembly in `lib/` needs to be compiled again AnyCPU, but there's an increased risk or issues because packages.config doesn't have different compile-time and runtime assets, the `lib/` files are both.

If it's at all possible to have the exact same managed code, and the only difference is in the unmanaged code, that simplifies the situation.

**Comment by obiwanjacobi** [comment]
I also try to solve the mismatched architecture problem. However, there is no way I am going to get an 'AnyCPU' build out of my mixed cpp/cli project and Roslyn is not gonna help either.
So what to do when you really only have an x86 and x64 (mixed) assembly?

**Comment by zivkan** [comment]
@obiwanjacobi This issue is about documenting existing behaviour, also this is the docs repo for NuGet. Your question requires a cross-team feature change, which is out of scope here. I'm sorry that this is not a satisfying answer, and I'm not trying to dismiss your concerns, but it's not going to get solved here. I suggest creating [a new suggestion on developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/content/idea/post.html?space=8), so we can more easily engage all the required teams within the company. Note that being a cross-team issue, it will require all the teams to prioritise and schedule the work, so I'm trying to set expectations that it might not get solved quickly (I'd love to be proven wrong).

**Comment by zivkan** [comment]
Oh, and if you're willing to take on additional work to resolve this using existing-features, you could take inspiration with [what the .NET BCL team do in the dotnet/runtim repo](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/ref/System.Net.Http.cs). They have a c# project which duplicates all the public APIs (without any implementation), which can be compiled with AnyCPU and put in the `ref/` folder. I know it's a lot of extra effort and complication in build scripts, and adds technical debt because hwen you change public APIs you're going to have to do it in at least two places.  But it's possible today.  This is assuming that the C++ compiler can't generate AnyCPU IL. I've done zero managed C++ development, but my memory from a quick test last year is that it can't do AnyCPU.


Finally, another idea which would require a one-time effort, rather than ongoing effort, is have a build script that builds your c++ project, then run a static analysis program or script which will generate an AnyCPU assembly from your compiled c++ assemblies. You could even have to compare the public APIs from the different architectures to make sure the .NET APIs are identical.

Last year, I started looking into both `System.Reflection.Metadata` and Roslyn's APIs to analyze assemblies and source coe, and once you "figure out" the APIs, neither is too difficult to use. You can [look at my efforts](https://github.com/NuGet/Entropy/tree/master/nuget-sdk-usage/nuget-sdk-usage) for a starting point.  My idea is to use these APIs to figure out all the public APIs, generate c# source code similar to the .NET BCL's reference assembly project, then compile that, either programatically (without a project file or sounce code on disk) using Roslyn's APIs, or write a temp project and `.cs` file on disk and run `dotnet build`.
