### ISSUE TITLE
Version difference

### ISSUE THREAD

**Issue by sbeaudoin** [NuGet/docs.microsoft.com-nuget#1112]
About obtaining the nuget version.  The VS help indicates 4.6.0 and $Host indicates 4.8.1.5434.  I think the $host returns the version number of the package manger HOST, not the version of nuget.exe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00fc5482-dc06-b48c-55e1-8f9e52593fbd
* Version Independent ID: fbdf8611-0864-cf5c-1d90-1ff9743d9f97
* Content: [NuGet Frequently-Asked Questions](https://docs.microsoft.com/en-us/nuget/policies/nuget-faq)
* Content Source: [docs/policies/NuGet-FAQ.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/policies/NuGet-FAQ.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
VS 2017 v15.6.0 and later report in Help/About that NuGet is version 4.6.0.
We've fixed this in VS 2019 16.0.0-preview2 where it properly show 5.0.0.

Package Manager Console always shows the exact version of NuGet (first 3 parts of version) and build number (4th part of version).

This is the issue that tracked this problem, that we fixed in 5.0.0 for VS 16.0.0-preview2: https://github.com/NuGet/Home/issues/7600
