### ISSUE TITLE
If you're doing this with .NET version 1, you need to run dotnet restore

### ISSUE THREAD

**Issue by mw44118** [NuGet/docs.microsoft.com-nuget#1151]
Starting with .NET Core 2, the restore command is run automatically.

But if you're still using Core 1, well, you better run dotnet restore, otherwise you will get a very confusing namespace not found error when you add that 

    using Newtonsoft.Json;

line into your code.

Otherwise, thanks for this tutorial!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bb0093-2809-50d2-f673-075530220d3d
* Version Independent ID: 2c0bb2fa-4df9-f8db-a5cf-f7d974b637d4
* Content: [Introductory Guide to Using NuGet Packages Through the dotnet CLI](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-using-the-dotnet-cli)
* Content Source: [docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
glad you like. thanks for the mention of netcore 1.x -- given the age of that, we won't be enhancing the docs for that....but thanks for the suggestion.

by the way, In NuGet 4.9 and .NET SDK 2.1.500, dotnet add package will now "commit" the restore it does, so that you don't need to do a restore before being able to use newtonsoft.json.
