### ISSUE TITLE
Dependencies not generated with nuget spec on project

### ISSUE THREAD

**Issue by jeffsdevinfo** [NuGet/docs.microsoft.com-nuget#1210]
The statement:
"Note: When creating a .nuspec from a project using nuget spec, dependencies that exist in that project are automatically included in the resulting .nuspec file."

Does not do any such thing.  Reviewing the generated .nuspec file after generating it based off the project file shows no dependencies when dependent packages are included in the built package.  Frankly the documentation for dependencies is poor.   Do we rely on PackageReferences, packages.config or only dependencies in .nuspec file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
@jeffsdevinfo I suspect the text you quoted may have been written before PackageReference existed, so I wouldn't be surprised if dependencies are automatically added only for packages.config projects. Hopefully at some point I'll find time to check and add a comment to the docs.

I'm not sure what you mean by this:

> Do we rely on PackageReferences, packages.config or only dependencies in .nuspec file?

Rely on for what purpose?

PackageReferences and packages.config are related to projects, while dependencies are related to a package. So, they don't have the same scope.

In case you're not already aware, if you're creating a .nuspec because you want to create a nuget package, if you're able to convert your project to SDK style projects, you can use `dotnet pack`, which will automatically generate the nuspec from project properties, including dependencies. Unless you have some advanced scenario that isn't supported by SDK project packing, or you're unable to migrate to SDK projects, then I suggest that using SDK projects to create your nupkgs is easier than creating nuspec files and packing yourself.

**Comment by StingyJack** [comment]
@zivkan - yes that text has been there for years (just search on the linked page to find it), and this has never worked properly. If you have a project that references 3 nuget packages and two other projects in the solution and you issue a `nuget spec` for that proj file, the resulting nuspec does not contain those 3 nuget packages as dependencies nor does it include the two other project outputs in the `files` element.

**Comment by StingyJack** [comment]
> dependencies are related to a package

@zivkan - this is not true. A project's referenced assemblies and referenced projects (and other artifacts) are also dependencies. They will also usually be a nuget package's dependency in one way or another. 

This is actually another example of the communication issues the NuGet team tends to create. Content Files vs contentFiles is a similar one.

**Comment by Mikejo5000** [comment]
Looks like a duplicate to #1135, which describes some different scenarios.

**Comment by Mikejo5000** [comment]
Updating docs, per #1135
