### ISSUE TITLE
Migration tool does not exist for Visual Studio for Mac

### ISSUE THREAD

**Issue by garie** [NuGet/docs.microsoft.com-nuget#1219]
Visual Studio Community 2017 for Mac
Version 7.7.1 (build 15)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e25f56-15c8-79d7-5e55-d145b7c1159c
* Version Independent ID: 06388a58-df68-9438-92d7-17359196f5c8
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference)
* Content Source: [docs/reference/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/migrate-packages-config-to-package-reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
@karann-msft @nkolev92 Any recommendations for non-VS scenarios? The doc referenced is VS-specific.

**Comment by nkolev92** [comment]
I think the customer should file an issue to developer community asking for this functionality in VS 4 Mac. 
NuGet team does not own that tooling. 
https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019

**Comment by Mikejo5000** [comment]
@garieIt looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this new functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2017) page.
