### ISSUE TITLE
nuspec depencies issue

### ISSUE THREAD

**Issue by galmok** [NuGet/docs.microsoft.com-nuget#1222]
When creating a nuget package that itself depends on other packages, that dependency can be loosely coupled by e.g. (in csproj):

    <PackageReference Include="Microsoft.ServiceFabric" Version="6.*" />

But looking inside the generated nupkg file for the generated nuspec file, this is what I see:

    <dependency id="Microsoft.ServiceFabric" version="6.4.617" exclude="Build,Analyzers" />

Obviously, the flexible dependency is not propagated onwards to the generated nuspec file. This is what we wanted to be generated:

    <dependency id="Microsoft.ServiceFabric" version="6.*" exclude="Build,Analyzers" />

We create nupkg packages like this:

    dotnet pack /property:PackageVersion=$packageVersion --configuration $Configuration --output $outputpath --verbosity normal $projectFilePath

We obviously do not use a nuspec file, but let dotnet pack extract the details necessary from the csproj file.

Is there something we missed or do we have to make post-pack editing of the nupkg file?

**Comment by zivkan** [comment]
As per [the docs on version ranges](https://docs.microsoft.com/en-au/nuget/reference/package-versioning#version-ranges-and-wildcards), the version string `6.4.617` means `version >= 6.4.617`, so it is "flexible". It's just taking a safe approach of setting the minimum version to the version that was used in the build, rather than setting the minimum version to 6.0.0 because 6.4.617 might have introduced new APIs not available in 6.0.0 which your package might be using.

The docs on version ranges explicitly says that the `*` wildcard can be used for `PackageReference`.  It explicitly says it doesn't work with `packages.config` and while it doesn't say anything about nuspec, given that it says PackageReference supports wildcards, that doesn't mean nuspecs do, but it is something that can be improved in the docs.

Does this answer your question?

**Comment by galmok** [comment]
I know what it means to specify a version in csproj files and in nuspec files and both support the * wildcard. You should read the document you linked. This is the example for the nuspec file:


<dependency id="ExamplePackage" version="6.*" />

PackageReference also supports the * wildcard.

Using a fixed version info as PackageReference in csproj which is used directly as a fixed dependency reference in nuspec is interpreted by the nuget package resolver as this version or later (no upper bounds). But the compiler/linker does not work like that and requires become to match exactly or to be specifically overridden (of possible).

For example: I have a project that loads two nuget packages (A and B) that both reference a third nuget package, but different versions (e.g 6.1 and 6.2). Individually, the two nuget packages work fine, but now the project won't compile due to two different versions of the third nuget package. The minimum requirement doesn't work. In the project I now have to reference a specific version of the third nuget package (6.2) to make the project compile, even though this project didn't directly use that third nuget package.

If that nuget dependency was written as 6.*, there would be no warnings and no need for the project to reference the third nuget package. This is tested and verified.

So again I ask: why isn't the range description for PackageReference used when writing the dependencies in the nuspec file?

**Comment by zivkan** [comment]
Oops, I'm new the team and didn't know that nuspec supported * wildcards. There's too many pages of docs to memorise everything already.

Unfortunately I don't understand the scenario you presented.

There's package C, which has versions 6.1 and 6.2
There's package B which depends on C >= 6.2 and package A which depends on C >= 6.1

If I create a project that uses packages A and B, NuGet will see package A's dependency on C has version range `[6.1,)`, package B has dependency range `[6.2,)`. I don't know if NuGet merges these into version range `[6.2,)`, or if it validates both version ranges separately when it gets the list of versions of package C that are available. In any case package C 6.2 will be selected. This either happens at restore time for PackageReference projects, or install time for packages.config projects.

If package A specified its dependency on package C as the version `[6.1]` or `[6.1,6.2)`, then NuGet will be unable to resolve a compatible version of package C when using packages A and B, but that will be a restore error rather than a compile error.

If you have seen an example where NuGet selected and restored version 6.1 when the project used another package that specified 6.2 as a minimum, then it sounds like a bug which I would be grateful if you could share a reproduction. On the other hand if Package A specifies a dependency on C versions 6.1 >= and there's a breaking change in 6.2, NuGet can't know this, so is unable to help avoid build or runtime errors. Package A's author has to set the max version of the C dependency to below 6.2.

Sorry if this message isn't clear, but if you're experiencing a problem, it would be much easier to understand if you could share a reproduction.
