### ISSUE TITLE
So PackageReference allows accidental updates that would break the application?

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#1224]
&gt; In projects using the packages.config management format, however, you can specifically constrain the version range. For example, if you know that your application works only with version 1.x of a package but not 2.0 and above, perhaps due to a major change in the package API, then you'd want to constrain upgrades to 1.x versions. This prevents accidental updates that would break the application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e755306-fb38-33c5-6f0f-1947832c21f2
* Version Independent ID: 0335cc14-e041-ffb3-f3c4-26dd39d18ef2
* Content: [Reinstalling and Updating NuGet Packages](https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages#constraining-upgrade-versions)
* Content Source: [docs/consume-packages/Reinstalling-and-Updating-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Reinstalling-and-Updating-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
[PackageReference supports version ranges](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#references-in-project-files-packagereference) although from my testing it produces warning NU1608. So, if you want it to break your build, you should configure your project(s) to treat NU1608 as an error.

**Comment by StingyJack** [comment]
So the docs are incorrect then?

**Comment by zivkan** [comment]
The paragraph you quoted explicitly says "In projects using the packages.config management format". While the docs could use improvement to help understand differences between packages.config and PackageReference, I had a quick look over the entire page and didn't notice anything wrong. If you believe there's something wrong, please be more specific. The sentence that says "This prevents accidental updates that would break the application" is, in my opinion, clearly referencing a packages.config specific feature. My previous comment about treating NU1608 as an error, rather than just a warning, is a tool that can be used to achieve a similar thing with PackageReference.

**Comment by StingyJack** [comment]
The specific point is in the title of this issue. The idea that is conveyed with the way its phrased is "packages.config prevents accidental updates that would break an application. Package reference does not prevent accidental updates that can break an application".  I wouldnt think something like that would be true, but I dont know as I cant use package reference.  

From your own shared experience, it sounds like it is partially true or true by default in that if you miss the warning or dont have warnings as errors it could break your application. As scary as that is as a default, it does address my thought that the docs were incorrect.
