### ISSUE TITLE
Need examples

### ISSUE THREAD

**Issue by zenakuten** [NuGet/docs.microsoft.com-nuget#1229]
"To be consumable in a C++ project, a package must target the native framework. "

How do I do this in a nuspec file?  There isn't any documentation I can find.    Please provide an example nuspec file for a native C++ dll.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae24ac6-e495-0b9f-9fc9-eef609e2492b
* Version Independent ID: 86486a38-2180-49aa-68ac-36f8dd0629e1
* Content: [Creating Native NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/native-packages)
* Content Source: [docs/create-packages/Native-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Native-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by MikeDiack** [comment]
Totally agree. This is almost worthless documentation, without an example and supporting commentary.

**Comment by tebeco** [comment]
bump ;)

I'm trying to package binaries given by a third part, as they don't when to release it as a `nupkg`.
Reading the docs was a deception :s

**Comment by thedevilfish** [comment]
Ok, after some digging here is how I found an example. 

1. I created a hello world C++ project in Visual Studio. 
2. I opened up Nuget package manager (right-click on `Project > Manage Nuget Package`).
3. I looked for `boost` which is a popular C++ library. I downloaded the package.
4. I navigated to my temp project and under the `packages` folder, I looked inside `boost`.
5. Next I used **Nuget Package Explorer** and opened the nuget package.

Voila! Now you have your example!

**Comment by tebeco** [comment]
I totally get your point, you are probably using the C++ way more than i would have dreamed about :s
This i what i did, with other package than boost
My experience with the C++ ecosystem is near to 0, and the binaries i have to package are already built by a third part vendor.
That vendor ships binaries for multiple platform/arc and also ship managed wrapper

In this scenario Boost won't help much better.
i tried with multiple package like SqLite
The thing is that since nuget 2.7 / 3.5 etc ... there was breaking changes in the folder structure of how nuget is scaffold so i can't just take a random package.

Once i got there the packing is not that straightforward when packing both managed/native binaries
* the nuget "downloaded" does not all respect the spec (warning or fail with latest nuget CLI)
* folder are supposed to match RID when doing XPlat but the random samples does not uses the same layout
* reference the package in .net project reference only a subset of what it should do
* native lib were sometime not loaded during debug
* native lib need to be copied on publish folder specific to the associated RID when running `dotnet publish --runtime RID`
* have to actually load x86 or x64 based on Build time parameter

That's a small list of what happen and that i can't guess randomly when picking  "boost" or "sqlite" or ....

We finally made it work after lots of efforts

That why i went here during the process and after because  even though we looked at the documentation we could not find detailed explanations about native/wrapper/rid/scaffolding
There are "notion" of it but not how to properly glue it together and make it work.

The point is not that that developper are looking for something to work.
The point was about giving developper a solid foundation of how it actually work written by the nuget team, They are doing an amazing work

 i believe that multiple developper can be stuck on this and are trying to take a look at the doc for that

**Comment by Mikejo5000** [comment]
#1013 has an example using .csproj

**Comment by tebeco** [comment]
@Mikejo5000 

yep looked at it as an "inspiration" but it's not always quite explicit about the layout / Xplat or the structure to adopt so that `dotnet publish --runtime ...` copy properly every binaries.
And then the same question shows up when you add managed wrapper.

We managed to have something that we think is working but it does not match what we found in the documentation.

Also the only doc i found about XPlat was in UWP section IIRC

just trying to use already existing issue to bump up an important point.
As .net core is going XPlat, there are chances that we might see native+wrapper package show up more and more

**Comment by Mikejo5000** [comment]
With a good working sample, as simple as possible, I could update the doc.

**Comment by tebeco** [comment]
yep
that could be used as a base example
An other uncovered part would be to explain how to package already existing native dll a vendor gives you.

i managed to have something packing but it also pack the `csproj` and the `obj` folder
i still don't understand why

the main issue is not only missing example but the documentation explaining how should we actually build the `.proj` itself in such scenario

or for example with with even
```
<NoBuild>true</NoBuild>
<NoRestore>true</NoRestore>
```
it still generate obj folder for the `dotnet pack` ?

**Comment by karann-msft** [comment]
@zenakuten @MikeDiack @tebeco @thedevilfish - I would suggest taking a look at VCPkg that is targeted specifically at this scenario - https://github.com/Microsoft/vcpkg#vcpkg

**Comment by tebeco** [comment]
i can't use VCpkg when third part vendor refuse to package binaries

they only ship 
* Win32/x64 native => raw `dll` file
* linux native specific => raw `so`file
* respectively x86/x64 managed wrapper => raw `dll`

**Comment by karann-msft** [comment]
We are rolling up all native and C++ related issues into #238.

**Comment by tebeco** [comment]
thx a lot for the info and the follow up

**Comment by MikeDiack** [comment]
Frankly this is rubbish. You've closed the issue. No documentation added. People are asking for help and you've done nothijng.
This appears to be the current state of things at Microsoft - same with bugfixes for VS.

Rubbish,

Mike

------ Original Message ------

**Comment by karann-msft** [comment]
@MikeDiack - we rolled this issue up to a single tracking issue for C++/Native scenarios instead of bunch of similar issues.
