### ISSUE TITLE
Do .snupkg files also need to be signed?

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/docs.microsoft.com-nuget#1253]
The doc doesn't specify if the new symbols format (.snupkg) needs to be signed before it can be pushed to nuget.org. https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg. Should they also be signed or do they not need signing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2a0cf1-bbb7-18f7-bfed-f717da4c1812
* Version Independent ID: 0e4df241-34c7-d943-5811-9ed0d40291f1
* Content: [Signing NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package)
* Content Source: [docs/create-packages/Sign-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Sign-a-Package.md)
* Product: **nuget**
* GitHub Login: @rido-min
* Microsoft Alias: **rmpablos**

**Comment by natemcmaster** [comment]
cc @skofman1 @anangaur - we're thinking of adopting snupkg in the aspnetcore build system. This question came up, and I couldn't tell from docs what the expectation is. Can you clarify?

**Comment by skofman1** [comment]
There is no need to sign snupkgs since there is no tool to verify it's signature. When you restore a package, nuget client verifies the package is valid using the signature, but snupkgs themselves are never downloaded (unless you do it manually from the website), they are used only for upload/sharing. The pdbs inside them are downloaded by the debugger that also verifies their hash. If in the future we add tooling around snupkg download and their signature validation, this might change.

**Comment by natemcmaster** [comment]
Great, thanks for confirming. Just wanted to be sure.
