### ISSUE TITLE
nuspec vs csproj for making nuget packages

### ISSUE THREAD

**Issue by SidShetye** [NuGet/docs.microsoft.com-nuget#1328]
There are two ways to create nuget packages - one using nuspec files and the other using sln/csproj files (e.g. `dotnet pack c:\my.sln /p:Version=1.2.3 -c Release -o c:\nuget`).

Both seem to have varying levels of support and also use different (but similar) xml syntax underneath. This adds to confusion, so I suggest you use just one approach and support/document it well.

Can you clearly document which approach is the officially supported / desired approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by StingyJack** [comment]
They are both "official". After making a few hundred packages I can offer this advice... If you have a simple package with a single dll and no other files, then use the csproj. Its easier. If you need anything outside of that I would strongly suggest the nuspec.   

Similar advice applies when using `dotnet pack`. If you have to build only .net core projects in a solution then you can use `dotnet`. As soon as you need to build both .net framework and .net core, you should use `nuget.exe` (version 4.9 or later).

The XML syntax for both is identical as its XML syntax. The MSBuild property names vary because they are not hierarchical.

**Comment by nkolev92** [comment]
@StingyJack 

I believe msbuild/dotnet pack satisifies a majority of the scenarios where 1 project is used to build the package.
We try to bring parity between the csproj pack and nuspec pack as mcuh as possible, so if you have scenarios that don't work with csproj pack/ you are not sure how they would work, we'd love to look into them and try to make it easier for customers by improving the docs/providing examples and even bridging a gap if a scenario is deemed important enough.

**Comment by themightyzek** [comment]
I'm trying to pack a Roslyn analyzer, which depends on a specific version of Microsoft.CodeAnalysis.Analyzers, because if an old version is used, it sometimes throws an NRE (see [this issue (off-topic)](https://github.com/dotnet/roslyn-analyzers/issues/1888)). 
I'm using the `<GeneratePackageOnBuild>` property (which I think results in dotnet pack being called) to generate the package.

I believe that due to the package reference being redundant (it's not actually being used), it gets omitted when the nuspec for the package is generated.

This is my csproj:
```xml
<ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.6.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.10.0" />
    <PackageReference Update="NETStandard.Library" PrivateAssets="all" />
</ItemGroup>
```

And this is the .nuspec in the resulting package:
```xml
    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.CodeAnalysis.CSharp.Workspaces" version="2.10.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```

Is there a way to force this reference to be included? I know it's possible by means of using a tokenized nuspec template, but I have refrained from using one, as the example analyzer project doesn't either.

**Comment by nkolev92** [comment]
The Microsoft.CodeAnalysis.Analyzers package is marked as a development dependency. 
That means that you cannot depend on the compile assets of that package and that package will not be included in your dependencies when you pack that project.

You can read more about it: 
https://docs.microsoft.com/en-us/nuget/reference/nuspec#developmentdependency
https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference and 
https://github.com/NuGet/Home/issues/4125

The bit that makes a package not be included as a dependency in the containing project's package is the PrivateAssets bit. 
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

So a few things. 


1. Analyzers are really meant to be standalone, and not bring any dependencies themselves.
1. Consider whether you really want to included that package as a dependency. The author has recommended you should not do that, since it's not a compile dependency. 
1. If you really think you want that dependency, play with the PrivateAssets bit :) 
You can always just include analyzers.
1. Make sure you test your resulting package :) 

Hope this helps.

**Comment by karann-msft** [comment]
@SidShetye - does that answer your question?

**Comment by Mikejo5000** [comment]
I believe recent updates to several topic, including this one, have clarified recommendations around .nuspec and dotnet pack/nuget pack.

See project type compatibility in this topic:
https://docs.microsoft.com/en-us/nuget/reference/nuspec#project-type-compatibility
