### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by nickniverson** [NuGet/docs.microsoft.com-nuget#1482]
I have some criticisms about the industry stance on not checking in NuGet packages.  But we'll first start with the issues with this article.

Regarding point #1.  
         "Distributed version control systems, such as Git, include full copies of every version of every file 
         within the repository. Binary files that are frequently updated lead to significant bloat and lengthens 
         the time it takes to clone the repository."

Who cares, we only clone once... However, this will force a package restore as part of the build process, which if you have a CI build, might run 50+ times per day or more!  Unless you can guarantee that packages won't be restored over and over again with every build.  This is a waste of resources and will ultimately cost you more money as you use more compute time in Azure Dev Ops.  The time wasted during a build is much more valuable that the one time cost of cloning a repository.  

Regarding point #2.  
         "When packages are included in the repository, developers are liable to add references directly to 
         package contents on disk rather than referencing packages through NuGet, which can lead to hard- 
         coded path names in the project." 

Once the packages have been restored, there is nothing stopping developers from doing this anyway.  So, this is a moot point in-my-fact (I don't have opinions ;) ... See what I did there... :) ).

Secondly, one would think that it would be a best practice that a solution should build on any developers machine upon pulling down the code from source control.  However, with a NuGet restore policy, this is not always the case.  For example, this assumes that NuGet will host all versions of all packages until the end-of-time.  

Packages restore does not work with custom package sources when new developers clone the repository.  This means that the solution will not immediately build without manual intervention and configuration.  

Forcing package restore is a bad-practice.  End of story.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d965aea9-a6cc-06da-a347-6e8c89458c98
* Version Independent ID: 6775f211-f4b6-6d0c-6f2e-6664b3e9721e
* Content: [NuGet Packages and Source Control](https://docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control#feedback)
* Content Source: [docs/consume-packages/Packages-and-Source-Control.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Packages-and-Source-Control.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nickniverson** [comment]
I've also noticed that since there are machine specific paths in the project.assets.json file.  So, if we want to migrate to the new csproj format then we're getting forced to require package restore.  Which means, that I now need to migrate packages from our internal private NuGet repo to something ADO can see.

**Comment by nickniverson** [comment]
https://blog.ploeh.dk/2014/01/29/nuget-package-restore-considered-harmful/

**Comment by loic-sharma** [comment]
Hello! You bring up several good points, so I'll try to address them individually.

> .. this will force a package restore as part of the build process, which if you have a CI build, might run 50+ times per day or more! Unless you can guarantee that packages won't be restored over and over again with every build. This is a waste of resources and will ultimately cost you more money as you use more compute time in Azure Dev Ops. 

This is indeed a problem! Azure DevOps will address with [Azure Pipelines caching](https://devblogs.microsoft.com/devops/adding-caching-to-azure-pipelines/).

> The time wasted during a build is much more valuable that the one time cost of cloning a repository.

I'm not sure that I follow. You still need to download your dependencies even if you add them to your Git repository. Your Git repository changes over time, so it's difficult to cache it. On the other hand, packages are easily cached as they are static files. I would expect better performance restoring dependencies through NuGet than Git. Also, keep in mind that Git repositories keep a history of all the files that were ever added. Adding dependencies to your Git repository will bloat the repository and dramatically increase initial Git clone times.

> .. developers are liable to add references directly to
package contents on disk rather than referencing packages through NuGet, which can lead to hard-
coded path names in the project."
> Once the packages have been restored, there is nothing stopping developers from doing this anyway. 

You're right that it's still possible, however, it is significantly harder. Reference package contents directly is a bad practice and makes it harder to upgrade your dependencies. NuGet is a layer of abstraction that prevents your developers from making this mistake.

> this assumes that NuGet will host all versions of all packages until the end-of-time.

That is correct. As a matter of policy, NuGet.org does not allow package deletes. In addition, you can guarantee repeatable builds using a [lock file](https://devblogs.microsoft.com/nuget/enable-repeatable-package-restores-using-a-lock-file/). If this isn't enough, you can always setup your own mirror of NuGet.org with the packages you depend on: https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

> Packages restore does not work with custom package sources when new developers clone the repository. This means that the solution will not immediately build without manual intervention and configuration.

You can check in a `NuGet.config` file with your desired NuGet sources preconfigured: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file

I hope I addressed your concerns. Please let me know if you have any additional questions!
