### ISSUE TITLE
Documented search phrases and "plus" operator do not work.

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/docs.microsoft.com-nuget#1702]
https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#search-syntax

**Phrases** with quotes don't work as they are documented and have not since even before Lucene search. Example:
https://www.nuget.org/packages/Base2art.Web.App.Configuration/

**Keywords** with plus symbols seems to have regressed since Azure Search. Example:
https://www.nuget.org/experiments/search-sxs?q=knapcode%2Btor

We should update the docs to reflect the current behavior.

**Comment by karann-msft** [comment]
@joelverhagen - can you please help with a PR :)

**Comment by joelverhagen** [comment]
@karann-msft - the next two sprints are planned. @skofman1 can set the priority of this.

**Comment by karann-msft** [comment]
@skofman1 - let's plan this for the next sprint.

**Comment by skofman1** [comment]
@karann-msft , regarding queries with quotes - makes sense to fix the docs since it haven't worked in ages, and we should definitely prioritize for next sprint.  
However, sounds like the plus issue is a bug introduced as part of Azure Search migration. 
@joelverhagen , is there a tracking issue for this on Gallery repo? What the complexity of this fix? If it's easy let's just fix next sprint. If not, let's discuss options.

**Comment by loic-sharma** [comment]
> What the complexity of this fix? 

I would estimate this as 1-2 days of work to `+`. However, in the last 30 days only ~50 different nuget.org search queries had the "plus" operator ([see this](https://ms.portal.azure.com#@33e01921-4d64-4f8c-a055-5bdaffd5e33d/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F685c4662-53d8-40f9-ac51-926097ede041%2FresourceGroups%2Fnuget-prod-0-v2gallery%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnuget-prod-v2gallery/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA1WOsQrCQBBE%252B4D%252FMFyVEBDBOhZiKwjay3FZkituT3ZXzsKPN5oisZ15w5vwVMvpTCYx6KZ6o4wkBIuJ1Hx64AA%252F5Hq%252F65ulZZ8IXQd3lFyU5EpewnjxAzl8KXoZcY85vpGkOzpY1knCQx1%252BytNkYI2ZdbtwDRbJeo3pi5iWaCNc65Dlrw6ZzUdWOLTzgz6qRQ62xqoPrEU1JewAAAA%253D)). Given its low usage, I suggest we update the docs instead of supporting this feature.

**Comment by skofman1** [comment]
Discussed offline. We will look at client historical usage and see if there was a drop in plus usage after Azure Search was introduced. If there was a drop - we fix. If there wasn't (cause it was never popular) - we remove plus from documentation.

**Comment by loic-sharma** [comment]
I was unable to use client data as it is hashed. I looked at the search services' telemetry for "plus" operator usages in the last 90 days; the [new service had ~400 unique results](https://ms.portal.azure.com#@33e01921-4d64-4f8c-a055-5bdaffd5e33d/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F685c4662-53d8-40f9-ac51-926097ede041%2FresourceGroups%2Fnuget-prod-ussc-azuresearch%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnuget-prod-azuresearch/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA41PwUrDQBC9C%252F7DY08JMSRSeig0Qg%252FiVVE8mAZZkiFZaTbZ2QltxY93Qyj16GFg5r15780wuYm8%252BNubHxw7YoKYPgC6H%252FEA3Q7RJm%252FiK2t1TygKqKfHN7yS5rrL3ldLs%252FNnWyvMy3QSsg0cCsjghY1to1Gzp8%252BJD1GouFQvE%252FEZz5qDpRB7VZXKqSqEZdklLkgPZCMXY4v7dX69wwVKs%252FijkQ4qURg4YPVgRRvroZAsh1y2ey11Rx5MLZ2g9vuk1On3Lv3I002l%252Fkb%252Bw3k2bowXY2uBW8QjD180j3cI74XsX%252Bb4RLxaAQAA), the [legacy service had ~30](https://ms.portal.azure.com#@33e01921-4d64-4f8c-a055-5bdaffd5e33d/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F685c4662-53d8-40f9-ac51-926097ede041%2FresourceGroups%2Fnuget-prod-0-v2v3search%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnuget-prod-v2v3search/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA9MoLcrRjFYKLE0tqlQISCxKzE0tSS0qVoqNVipUitXk5apRKM9ILUpVKFQoLkksKikuzyzJUFDSVlLILwKKAQA3PninPwAAAA%253D%253D/timespan/P1D). I've opened this issue to fix this regression: https://github.com/NuGet/NuGetGallery/issues/7802

**Comment by loic-sharma** [comment]
It seems like the "plus" operator does not work on Visual Studio. See: https://github.com/NuGet/Home/issues/9043
