### ISSUE TITLE
How to copy references loaded dynamically?

### ISSUE THREAD

**Issue by vaibhav-gawali** [NuGet/docs.microsoft.com-nuget#1726]
How to copy reference DLL's that are loaded dynamically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efe48ec-f0f0-de4b-1c07-af1cc5c87d94
* Version Independent ID: fec47e16-9c71-8b73-0a41-d6808ac14700
* Content: [Select Assemblies Referenced By Projects](https://docs.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects)
* Content Source: [docs/create-packages/Select-assemblies-referenced-by-projects.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Select-assemblies-referenced-by-projects.md)
* Product: **nuget**
* GitHub Login: @zivkan
* Microsoft Alias: **zivkan**

**Comment by zivkan** [comment]
If you're using SDK style projects (or PackageReference on non-SDK style projects), then you could put the assemblies in the `runtimes/<rid>/lib/<tfm>/` directory.

Otherwise (consuming projects use packages.config) you'll need to [bundle your own msbuild props and/or targets file](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#include-msbuild-props-and-targets-in-a-package), and copy the assembly there.

Alternatively, don't use this assembly reference feature. That way the project will get an implicit `<Reference ... />` to the assembly and will always be copied.
