### ISSUE TITLE
NU5131 is now an error, not a warning

### ISSUE THREAD

**Issue by bgavrilMS** [NuGet/docs.microsoft.com-nuget#1734]
This is now an error, not a warning.

**Comment by karann-msft** [comment]
@zivkan - NU5131 is a warning right?

**Comment by zivkan** [comment]
NuGet raises it as a warning, yes. If the project opts into "warnings as errors", it will be raised as a error, as requested.  @bgavrilMS Can you check your project to see if warnings are elevated? It might be in a `Directory.Build.props` file, or another imported file, rather than the project file directly. Since you're Microsoft internal, you can reach out directly if you need help checking your project.

**Comment by karann-msft** [comment]
@bgavrilMS, I believe the docs are accurate. If you have specific product isues, please open a bug on the nuget home repo - https://github.com/nuget/home/issues
