### ISSUE TITLE
New WPF App(.NET Core) project missing references

### ISSUE THREAD

**Issue by Strydir** [NuGet/docs.microsoft.com-nuget#1837]
I apologize if this is covered somewhere else, but I haven't found any references to it.
The only references that I come across state that I need to "Allow NuGet to download missing packages" and "Automatically check for missing packages during build in Visual Studio".  Both options are/were checked, but every time I start a brand new WPF App(.NET Core) project I get this message: 
"Some assembly references are missing.  Building to restore the NuGet cache might resolve this issue".

It's a fairly new install of VS2019 ver 16.4.2 and I've only used it for some Forms tutorials.  That part of VS2019 works fine for me.
I'm new to VS2019 so I may be missing something simple?  
Thank you!
Windows10.
ps: I'm not sure how to "build to restore NuGet"...

Edit: in checking the VS installer, it installed with issues: VisualStudio.LiveShare did not install because... it already exists... Impacted workloads: .NET desktop development.
I'm attempting a 'repair'.

**Comment by karann-msft** [comment]
@Strydir - this repo if for nuget docs and filing issues with the NuGet documentation - https://docs.microsoft.com/en-us/nuget/ and not meant for product related bugs or questions.

Since your issue seems to be specific to WPF in Visual Studio, I would recommend looking at Developer Community for similar issues and the resolution provided there first - https://developercommunity.visualstudio.com/. If you don't find any similar issues, please file one on Developer Community.

**Comment by Strydir** [comment]
My apologies!
