### ISSUE TITLE
Missing Edge Case

### ISSUE THREAD

**Issue by SaltyCybernaut** [NuGet/docs.microsoft.com-nuget#1916]
If 'References' exists in a project, the option to migrate from Packages.config to PackageReference will not appear in the right-click context menu unless the file 'packages.config' exists in the project. packages.config can even be an empty file with not data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a154e5f-436d-6297-ec05-4d134a2404f9
* Version Independent ID: 1c782e82-db9a-bf77-05ef-cd49374aee36
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#package-compatibility-issues)
* Content Source: [docs/consume-packages/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/migrate-packages-config-to-package-reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
Having a reference in your project file to an assembly in your packages folder, without a `packages.config` file is not a supported scenario. The most obvious ways to get into this state are 1. manually add the reference to the assembly, rather than using Visual Studio's Package Manager UI or Package Manager Console, or 2. install the package in a supported way, then delete the packages.config file.

@karann-msft what's your advice on documenting that a feature doesn't work, when the project isn't correctly using `packages.config`?

**Comment by karann-msft** [comment]
@zivkan - I suggest adding a para that talks about common ways to get into a bad state such as the ones you call out.
