### ISSUE TITLE
Please document how to use local feeds using dotnet CLI

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/docs.microsoft.com-nuget#2075]
It's unclear how to use the dotnet CLI to push to local feeds. The closest I found is this: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push#examples

![image](https://user-images.githubusercontent.com/737941/85347886-c1fb4300-b4ae-11ea-9739-7d8cfa7cd822.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72d49ada-7a7b-e976-88a0-72ad0707dbd8
* Version Independent ID: dcc2b12a-4da9-8e7b-f973-e49347030651
* Content: [Setting up Local NuGet Feeds](https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds)
* Content Source: [docs/hosting-packages/Local-Feeds.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/hosting-packages/Local-Feeds.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by ClaudioFriederich** [comment]
The above command actually **will** store packages in a hierarchical folder structure if the c:\mydir has at least one package already in it that is stored in a hierarchical folder structure.  If the folder is empty, go to the global cache folder at %user%\.nuget\packages, and choose a top-level package id folder in it, doesn't matter which one.  Just make sure it is a "simple" individual package, not a package like .net standard or .aspnet that encompasses an entire framework.  Copy that folder into the empty c:\mydir folder.  Then do the dotnet nuget push ... command.  Then, you can delete the folder you just copied in.  From hereon out, your folder will have at least one package in hierarchical folder format, and that format will be used from then on.  It is a silly kludge - dotnet nuget push should just have a command line switch to use /v3/ format instead of /v2/ by default, but it works.
