### ISSUE TITLE
nuget.config casing

### ISSUE THREAD

**Issue by odalet** [NuGet/docs.microsoft.com-nuget#2144]
It's not very clear what the correct casing of `nuget.config` should be:
* I've stumbled across various (old) Github issues discussing this, but didn't find (or search long enough) a definitive answer to this
* [This page](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file) mention both `nuget.config` and `Nuget.Config` (and not `Nuget.config`).

Now that .NET is heavily used on case-sensitive platforms, I think it'd make sense to indicate what the official file name is (doesn't prevent tools from being lax though).

Thanks!

PS: In the meantime, I suppose I'll go with `nuget.config` the same way I have `packages.config`...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Common NuGet configurations](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
This is mostly an old issue that has been resolved since. The preference of names [comes from this code](https://github.com/NuGet/NuGet.Client/blob/97311b5cb48d38402b49fd41a6384b11db7dd453/src/NuGet.Core/NuGet.Configuration/Settings/Settings.cs#L34-L36)

Thus `nuget.config` is the preferred best practice, followed by `NuGet.config`, and lastly by `NuGet.Config`.

If something doesn't work, please let us know in an issue on:

https://github.com/NuGet/Home/issues

Given there are no known issues & this guidance already exists in docs, I'm closing this issue.
