### ISSUE TITLE
Clarify the correct NuGet test address

### ISSUE THREAD

**Issue by mbranscomb** [NuGet/docs.microsoft.com-nuget#2174]
Topic [NuGet.org frequently-asked questions](https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq) refers to using 
https://int.nugettest.org/ to test/validate packages before uploading to NuGet.org while other references or issues elsewhere refer to https://dev.nugettest.org/.

Please can you clarify the relationship of these two services and clarify which one is most appropriate for package testing/validation prior to publishing on NuGet.org?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3d036ff-c905-3f12-3839-6288efc0a978
* Version Independent ID: 3ec60a82-768a-57a4-b73f-eee2ae0d014f
* Content: [NuGet.org Frequently-Asked Questions](https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq)
* Content Source: [docs/nuget-org/nuget-org-faq.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/nuget-org/nuget-org-faq.md)
* Product: **nuget**
* GitHub Login: @shishirx34
* Microsoft Alias: **shishirh**

**Comment by JonDouglas** [comment]
@joelverhagen or @loic-sharma Can either of you comment on the differences here & I'll get this added to the docs?

**Comment by joelverhagen** [comment]
dev.nugettest.org can be very flaky since we push private (unreviewed) changes there sometimes. int.nugettest.org is the proper integration environment to be mentioned in docs. Neither have the SLO or monitoring that nuget.org has. They are both "test" environments with no strong focus on availability or data retention.

That being said, we should understand the scenarios that necessitate int.nugettest.org use by customers and make sure these things wouldn't better fit on nuget.org itself.

**Comment by joelverhagen** [comment]
For example, I'd like to have a feature that allows better validation of packages prior to release (https://github.com/NuGet/NuGetGallery/issues/8283), but int.nugettest.org has worked for some people in this case.

**Comment by joelverhagen** [comment]
Let's close this for now with the following conclusion:

**Feel free to use int.nugettest.org for testing, per [the FAQ](https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#is-it-recommended-to-upload-my-test-packages-to-nuget-org).** Avoid using dev.nugettest.org.

I'd like to avoid mentioning dev.nugettest.org ("DEV") since it's even more flaky that int.nugettest.org ("INT") and we try to avoid pointing any customers at all to it. There is very likely several references to DEV on GitHub or elsewhere, but I don't see any in the docs. I'd like to keep it that way.

Internally, we use DEV for testing builds even before pull request and it often breaks or has weird problems.
