### ISSUE TITLE
Nuspec.xsd schema URLs are not hosted - clarify the "latest" version and plan

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/docs.microsoft.com-nuget#2195]
These nuspec schemas were never hosted. 
We need to explain in these docs, that `SchemaVersionV6 = "http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd"`
is our latest schema, and we likely won't change it going forward. However, github can change the schema hopefully in a way that doesn't break old clients.

I suggest:

- Explain how V6 works

- Update all the URLs to the latest, and list the older versions as legacy support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @JonDouglas 
* Microsoft Alias: **JODOU**

**Comment by zivkan** [comment]
I believe nuspecs works without a xml namespace. This should be validated, and examples changed to not use the namespace, rather than using the latest URI (it's not a URL), assuming it works.

**Comment by abatishchev** [comment]
@JonDouglas @donnie-msft please reopen. And remove the damned bot, it doesn't help.

**Comment by JonDouglas** [comment]
Although I don't like the bot either, I would still likely close out this issue due to inactivity over 2 years and no upvotes nor community engagement. What would you propose here? We can reopen and mark as up for grabs or similar.

**Comment by abatishchev** [comment]
@JonDouglas in my mind there can be only two reasons to close an issue:

1. It has been addressed
2. It won't be addressed

What I disagree with is the notion of *community engagement* as a metric whether to close an issue or not. Because it doesn't mean the issue will be actually addressed but merely kept open. How many of the most voted (and oldest) issues in this repo have been addressed lately? Respectfully, just a rhetorical question.

Going back to the issue, I think it still stands. You're proposing to mark it *up-for-grabs*. But who other than the NuGet team and the Microsoft org behind it should host the schema (and invest into maintaining the hosting long-term)?

**Comment by ChristopherHaws** [comment]
Can you clarify, how are you supposed to get autocomplete and validation in VS Code if the schema file doesn't exist? I get the following error in VS Code when trying to edit my `nuspec` file:
![Uploading image.png…]()

**Comment by abatishchev** [comment]
@donnie-msft, @JonDouglas ping

**Comment by JonDouglas** [comment]
There are no plans to address this issue at this time.

**Comment by abatishchev** [comment]
@JonDouglas same applies pretty much to any other issue in the NuGet space on GitHub. Thanks!
