### ISSUE TITLE
Creating UWP NuGet package screenshot(s) are incorrect

### ISSUE THREAD

**Issue by marcelwgn** [NuGet/docs.microsoft.com-nuget#2198]
I have followed the steps outlined in the documentation, however the nuget package does not seem to be correct at all:

![image](https://user-images.githubusercontent.com/16122379/97655120-af000d00-1a64-11eb-91bf-c593102cd750.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5fec3de-a394-d04f-4e21-9afa19ece12c
* Version Independent ID: 921bd8f6-d85d-10b7-5924-734351dc1fd4
* Content: [Create NuGet Packages for the Universal Windows Platform](https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages-cs)
* Content Source: [docs/guides/Create-UWP-Packages-CS.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/Create-UWP-Packages-CS.md)
* Product: **nuget**
* GitHub Login: @rrelyea
* Microsoft Alias: **rrelyea**

**Comment by MarcelGosselin** [comment]
@nkolev92 I believe you meant to ping @chingucoding in your comment. We have the same first name though.

**Comment by nkolev92** [comment]
Oh my bad haha :D

I definitely meant to tag @chingucoding 
I naively got tricked by GH's autocomplete :) 

Thanks for letting me know!

**Comment by chingucoding** [comment]
Almost thought that but the fact that @MarcelGosselin also contributed to the repo left me wondering what the intention was 😄 

Regarding the issue, I think the issue is that the screenshot in the docs shows the nuget package containg dll and pri files and not having warnings. However presumably, following these steps I ended up with the result as shown above: only winmd and pri files and errors/warnings being indicated for the nuget package. But I have to admit that my memory on this is quite faded now and I might be missing some things (or I did make a mistake back then?).

**Comment by nkolev92** [comment]
Are you referring to the source link and deterministic build warnings that NuGet Package Explorer is showing?

**Comment by chingucoding** [comment]
Yes, exactly but I assume those are not that important are they?

**Comment by nkolev92** [comment]
NuGet Package Explorer is a great tool for people that create packages, because it captures way more than just then the package itself and its metadata. 

For example, it inspect assemblies etc.

So the answer about the importance is that it really depends where you're publishing the package. There's way more detail at https://github.com/dotnet/sourcelink. 

However, none of those warnings would make a package unusable.

**Comment by chingucoding** [comment]
I see, thank you for the insights! And what about the lack of dlls but the existence of the winmd files? Do you happen to know if that is expected (I assume so given how UWP works but not sure about that).

**Comment by nkolev92** [comment]
Yeah, UWP uses winmd files, I'm not an UWP expert though.

**Comment by chingucoding** [comment]
But shouldn't the screenshot in the documentation include winmd files then?

**Comment by nkolev92** [comment]
Can you clarify which screenshot you're referring to?

**Comment by chingucoding** [comment]
> Can you clarify which screenshot you're referring to?

Sure thing, the screenshot in this section: https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages-cs#package-the-component

**Comment by chingucoding** [comment]
> Oh I see it.
> 
> The nuspec and what the screenshot is representing are conflicting.
> 
> Do you mind if we retitle the issue?
> 
> I don't think there's a problem with the package, but rather the docs do not match.

Of course, sure!

**Comment by nkolev92** [comment]
That's perfect thanks.
