### ISSUE TITLE
Instructions for nuget for the Mac are incorrect.

### ISSUE THREAD

**Issue by gitclem** [NuGet/docs.microsoft.com-nuget#2219]
I believe the examples of things to execute for the Mac are WRONG!

E.g. `nuget` on the mac is simply `nuget` not `nuget.exe`

And getting nuget for windows doesn't make sense.

Also when updating nuget on the mac you have to use sudo:

`sudo nuget update -self`

Somebody should double check all the Mac specific instructions to make sure they really work on the Mac.  I see several copy and paste errors.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3460a9b2-3b49-1cda-add2-14d26e217716
* Version Independent ID: 95b91106-faff-c7f6-3699-94d643b5cf73
* Content: [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)
* Content Source: [docs/install-nuget-client-tools.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/install-nuget-client-tools.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
Thanks for the issue!

When you alias the `nuget.exe` on Mac, you can use just `nuget` because that is your alias name. If you do not alias it, you would have to call `mono nuget.exe` to use nuget.exe on Mac.

I'll add a note to include `sudo` usage on MacOS for `update -self`.

What about getting NuGet for Windows doesn't make sense? Also what examples are wrong? At first glance they seem okay to me.
