### ISSUE TITLE
how to specify hotname

### ISSUE THREAD

**Issue by quantrpeter** [NuGet/docs.microsoft.com-nuget#2230]
Hi
    how to specify hotname? my nuget server is standing behind apache by proxy pass.
Thanks
Peter

**Comment by JonDouglas** [comment]
If your issue is a question then please ask the question on [Stack Overflow](https://stackoverflow.com/questions/tagged/nuget) using the tag `nuget`. Additionally, you can ask a question using [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/dotnet-package-management.html) under the `package management` section.

For example you might find: https://stackoverflow.com/questions/9232160/nuget-behind-a-proxy which can help.

**Comment by quantrpeter** [comment]
i resolved it by apache sslproxypass, i was using proxypass which is not working
