### ISSUE TITLE
Long Path Support in Visual Studio

### ISSUE THREAD

**Issue by ncook-hxgn** [NuGet/docs.microsoft.com-nuget#2323]
Hello,

I was wondering if theres anything in the pipeline to support Long Win32 Paths in Visual Studio so that it can fully take advantage of the nuget ability to do so?

I have devs struggling to install packages via Visual Studio at the moment because of this issue, and not all of them are keen to dive into a commandline or Package Manager Console to install or update packages..

Thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08164af9-c614-f64e-d2d9-af037cab9c30
* Version Independent ID: 7a4a326f-718e-d923-b325-81f76b72c296
* Content: [NuGet CLI Long Path Support](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-long-path)
* Content Source: [docs/reference/cli-reference/cli-ref-long-path.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-long-path.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
We have the following doc for NuGet:

https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-long-path

And the issue here: https://github.com/NuGet/Home/issues/3324

For Visual Studio to support this, please upvote the following issue: https://developercommunity.visualstudio.com/idea/351628/allow-building-running-and-debugging-a-net-applica.html

Please feel free to add your feedback to the issues above to help us understand your need of long path support.
