### ISSUE TITLE
error restore package

### ISSUE THREAD

**Issue by elmarkos23** [NuGet/docs.microsoft.com-nuget#2326]
Hello, I am using visual studio 2019. the error appears I am working on new changes to my xamarin forms application that I had 1 year ago and now I want to update the packages and I have this error

![image](https://user-images.githubusercontent.com/5819030/108565397-9ac17380-72d2-11eb-96ab-918f091f1fa8.png)

**Comment by elmarkos23** [comment]
Help me!

**Comment by JonDouglas** [comment]
Please see our contributing documentation:

https://github.com/NuGet/Home/blob/dev/CONTRIBUTING.md#before-submitting-an-issue

Because this is a question, we recommend that you post this issue on [Stack Overflow](https://stackoverflow.com/questions/tagged/nuget) or [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/dotnet-package-management.html)
