### ISSUE TITLE
Improve documentation on creating native packages

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#238]
Information in the existing topic is sketchy, and there are questions, see https://docs.microsoft.com/en-us/nuget/create-packages/native-packages#comments-container.

Request: "Needs more details of what package structures need to be and links to other reference material. "

Older issues:
https://github.com/NuGet/Home/issues/1508
https://github.com/NuGet/Home/issues/3027

Additional customer feedback:

1. Needs more details of what package structures need to be and links to other reference material.
2. I need to download a package. But nowhere I can do this.
3. More information about how to actually create a native package (use CoApp or not?)
4. It's painfull to create even a simple NuGet native package. Writing the props/targets files is just like the hell (it should be generated like with CoApp). Someone at Microsoft has pointed me on https://github.com/Microsoft/vcpkg (great but) the NuGet package stuff is just for local use (it's a bridge on the native files); no way to create a standalone package for publishing on the official repository :-(.
5. How would the creation of the nuspec file and the packaging look like? At the moment, when creating the nuspec (via nuget spec) and package afterwards (via nuget pack) nuget (v 3.5) just takes everything that sits inside my project folder and packages that. The assembly is missing etc. The CoApp project is dead and I haven't found anything on the roadmap for nuget (https://github.com/NuGet).

**Comment by kraigb** [comment]
See also https://github.com/MicrosoftDocs/mvp-hackadoc-2018/issues/43

**Comment by ras0219-msft** [comment]
>no way to create a standalone package for publishing on the official repository :-(.

Take a look at our `export` command [1][2].

[1] https://blogs.msdn.microsoft.com/vcblog/2017/05/03/vcpkg-introducing-export-command/
[2] https://github.com/Microsoft/vcpkg/blob/d80dd5cbc777ce765c2d6b78d7c485fdf05f284b/docs/users/integration.md#export

**Comment by kraigb** [comment]
What we really need is someone familiar with the process using vcpkg to draft a walkthrough that demonstrates the whole process of creating a native package. That expertise unfortunately does not seem to exist within the NuGet team. I can provide editing help and bringing the draft up to docs quality. Just create a branch with the work in it and we can go from there.

**Comment by kraigb** [comment]
Also addres #190, #592, and #600.

**Comment by ericstj** [comment]
Just hit this myself when trying to tell folks to use `nativeassets`.  Can we please get docs for this feature that's been around for 2 years now? /cc @jainaashish @rrelyea

**Comment by Mizux** [comment]
my 2 cents for "Building a cross-platform .NetStandard2.0 package with native dependencies" (only using dotnet/cli and modern .csproj)

I add my own way to do it there https://github.com/NuGet/docs.microsoft.com-nuget/issues/1013#issuecomment-414930782
And example project in https://github.com/Mizux/dotnet (Documentation on the way)

Still, waiting for the official documentation !!!

**Comment by jjpepper** [comment]
Does anyone know if there is a way of making native libraries specified in a targets file not appear in the solution view?

**Comment by Mizux** [comment]
@jjpepper why do you use/hack a target file instead of setting it in the `.*proj` file ?
And did you try the `<Visible>` property (which should work in `.*proj`) ?
src: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2017#content

**Comment by Mizux** [comment]
still not resolved officially...

**Comment by tebeco** [comment]
I'm really curious about a `dotnet pack` solution when vendor just gives you `MyNative.dll` and `MyDotnetWapper.dll`, refusing to create `nupkg`.

That's also a VERY common scenario for "legacy" nuget or third part that was used thx to `<Reference` and truing to move forward to `<PackageReference` by manually repackaging already built dll.
They are supposed to be repackaged to `netstandard2.0` since some could target `net47x` for example.

As of today i never found a clear and clean solution :(

**Comment by karann-msft** [comment]
Not eligible for docs day.

**Comment by tebeco** [comment]
hello @karann-msft 
would something like this helps as a support for documentation ?
https://github.com/NuGet/Home/issues/9502

This repository show a "way" that vendor uses (that is bad ... as they gives us RAW .net dll)
https://github.com/tebeco/NativeLibNugetStuff/blob/master/README.md

The original repo from @poke, shows a better way => properly packing the `native + managed`, it only depends on what you have on your hands
https://github.com/poke/NativeLibNugetStuff

I think both could be a good contribution to the the docs as it would helps vendor to have something to rely on, in order to release fully functional packages compliant with `dotnet restore` and `dotnet publish`

**Comment by Mizux** [comment]
FYI I've updated https://github.com/Mizux/dotnet-native to add "real" C++ samples code up to the .Net wraapper generation and I've updated my documentation accordingly.

**Comment by tuket** [comment]
What is the difference between "nativeassets" and "native" folders? What is the expected directory structure?

**Comment by Mikejo5000** [comment]
Ported to: https://github.com/NuGet/Home/issues/13594
