### ISSUE TITLE
The version doc may be misleading if read strictly top down - https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-basics

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#2414]
In particular https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-basics may lead someone to believe that prerelease versions with leading `0`s are ok. 

For example `1.0.0-0123` is not valid.

**Comment by StingyJack** [comment]
It's not valid for *you* maybe. It's nice that you want us to use semver, but don't force it. Sometimes we can't, or it's cheaper to not use it than to try to fix it (which is what happened when you released this breaking change in a minor version nuget update, customer had to reprint and revalidate part of a system because the component package version we told them was not the exact version  they got. Pharma companies are sticklers for this kind of thing and for good reason)

**Comment by nkolev92** [comment]
@StingyJack 

`1.0.0-0123` has not been a valid version in any version of NuGet. 
There are no changes to any behavior here, just better clarifying the doc. 

- 5.10.0-preview.2 - https://nugettools.azurewebsites.net/5.10.0-preview.2.7185/parse-version?version=1.0.0-0123
- 4.9.4 - https://nugettools.azurewebsites.net/4.9.4/parse-version?version=1.0.0-0123
- 3.5.0 - https://nugettools.azurewebsites.net/3.5.0/parse-version?version=1.0.0-0123
- 2.14.0 - https://nugettools.azurewebsites.net/2.14.0/parse-version?version=1.0.0-0123
- 2.7.0 - https://nugettools.azurewebsites.net/2.7.0/parse-version?version=1.0.0-0123
