### ISSUE TITLE
The NuGet Dependency Resolution documentation is very misleading

### ISSUE THREAD

**Issue by gaborposz** [NuGet/docs.microsoft.com-nuget#2434]
The documentation of the _"Nearest Wins"_ and _"Cousin dependencies"_ rules in the NuGet _"Dependency Resolution"_ chapter is very misleading.

Let's try to interpret the following sentences:
_"When the package graph for an application contains different versions of the same package, NuGet chooses the package **that's closest to the application in the graph** and ignores all others."_

_"When different package versions are referred to **at the same distance** in the graph from the application, NuGet uses the lowest version that satisfies all version requirements"_

Based on these I would assume that the _"Nearest Wins"_ rule is a general rule, and hence it is "stronger" than the _"Cousin dependencies"_ rule.

E.g.:
- My Project -> PackageE -> Package D (>= 1.1.0)
- My Project -> Package D (>= 1.0.0)

Here it's quite obvious that the **1.0.0** version of Package D is selected, since its version was "overwritten" by the user. (And by the way the NU1605 warning is displayed, since the package was downgraded.)

But let's take the following example now:
- My Project -> Package A -> PackageE -> Package D (>= 1.1.0)
- My Project -> Package A -> Package D (>= 1.0.0)

Based on the documentation I would expect that here again the 1.0.0 version is choosen (although that would be very weird), but in reality the _"Cousin dependencies"_ rule wins, and the **1.1.0** version is selected.

There are many discussion regarding this question (e.g.: #5400, #8020, #9861), but due to the many contradicting statements I had to try it out myself to be sure.

Both Package A 1.0.0 and Package B 1.0.0 references the **1.0.0** version of Package D:

![NuGetDowngradeCheck01_SolutionExplorer](https://user-images.githubusercontent.com/47426565/118299534-28cb8580-b4e1-11eb-9f63-a5c8c716d526.png)

But if I upgrade Package B to 1.1.0, then it will reference Package C 1.1.0, and that will reference Package D 1.1.0.

As you can see - although the Package D 1.1.0 reference is further from my application than the Package D 1.0.0 reference - the **1.1.0** version was choosen globaly:

![NuGetDowngradeCheck02_SolutionExplorer](https://user-images.githubusercontent.com/47426565/118299592-397bfb80-b4e1-11eb-9334-0724a20bd615.png)

Therefore it should be made clear in the documentation that the _"Nearest wins"_ rule is applied only on direct dependencies (aka. top level packages), and "Cousin dependencies" is **not** only applied _"at the same distance"_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8a945e-ee7e-cefa-282a-41da09a951b9
* Version Independent ID: c380b1cb-6e17-7777-995f-7c8b48f581de
* Content: [NuGet Package Dependency Resolution](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution)
* Content Source: [docs/concepts/Dependency-Resolution.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/concepts/Dependency-Resolution.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by madelson** [comment]
> "Nearest wins" rule is applied only on direct dependencies (aka. top level packages)

If this is true, then the example in the docs under "Nearest wins" regarding package C 2.0 should be removed as it is entirely misleading.

In fact, if this is the case then I think the docs should be changed as follows:

(1) Put the "cousin dependencies" section first
(2) Follow that with a section called "Direct dependencies win" that just says: "If the application directly references a package, the directly referenced version will be used even when the "cousin dependencies" rule would select a different version..."

**Comment by madelson** [comment]
@nkolev92 even if we're not ready to write the formal docs, any chance you could explain how this works here? This ambiguity is impacting our ability to write some internal tooling that works with NuGet.

**Comment by marcin-krystianc** [comment]
Hi, I've been looking at this recently as well an I've prepared this diagram. I hope it helps:

![image](https://user-images.githubusercontent.com/2308005/124891858-a68ba900-dfd9-11eb-9791-ae6be822d7af.png)

- Package `B v2.0.0` is considered “nearest” because both `B v1.0.0` and `B v2.0.0` are in the subtree of `Lib1` and  `B v2.0.0` is a direct dependency of `Lib1`. 
- On the contrary package `D v1.0.0` is closer to the root project than the `D v2.0.0`, but it is not considered “nearest”. It is because the `D v1.0.0` is a direct dependency of `B v2.0.0`, but `D v2.0.0` is not in the subtree of `B v2.0.0`.

**Comment by gaborposz** [comment]
@marcin-krystianc: I don't really get your point.
Is Lib1 also a NuGet package, or is it a library in your solution? (I.e. what do we consider "top level dependency" in this case, Lib1 or package A & B?
And which versions of package B and D would be choosen by NuGet at the end?

**Comment by marcin-krystianc** [comment]
Yeah, I know that this topic is hard to explain 😄
- `Lib` can be a project or a NuGet package, it doesn't really matter for the dependency resolution algorithm
- Don't think in terms of  "top level dependency", it is not how the algorithm works - that is what probably confuses you
- `B v2.0.0` is chosen due to "nearest wins" rule for the reason I explained in previous comment
- `D v2.0.0` is chosen because it is a cousin with `D v1.0.0` and ["NuGet uses the lowest version that satisfies all version requirements"](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#cousin-dependencies) (which is `D v2.0.0" in this case).
- Documentation claims that distance from the top level project is important but it is not how the algorithm actually works. `D v2.0.0` is selected even though it is further from the top level project than `D v1.0.0`.

**Comment by madelson** [comment]
@marcin-krystianc thanks for responding here. I feel like I'm still not quite understanding when the "nearest wins" rule gets applied.

In the diagram, for example, you say that B v2 is "nearest" but in this case B v2 is also the "lowest version that satisfies all requirements" (presuming that Lib 1 references B  >= v2).

* Can you show/describe an example where "nearest wins" trumps "lowest version that satisfies all requirements"?
* Is there a succinct way (like the current docs) that can describe the resolution algorithm accurately?

**Comment by marcin-krystianc** [comment]
> In the diagram, for example, you say that B v2 is "nearest" but in this case B v2 is also the "lowest version that satisfies all requirements" (presuming that Lib 1 references B >= v2).
> Can you show/describe an example where "nearest wins" trumps "lowest version that satisfies all requirements"?

If in the diagram that I posted above you would swap `B v1` and `B v2` it would be what you ask for. The `B` that is a direct dependency of `Lib1` is "nearest" in the scope of the whole `Lib1` subtree, so it always wins with any other "B" that is further down in that subtree.

> Is there a succinct way (like the current docs if they weren't inaccurate) that can describe the resolution algorithm accurately?

Nothing I'm aware of.

**Comment by nkolev92** [comment]
> Documentation claims that distance from the top level project is important but it is not how the algorithm actually works

I wasn't around when the original docs are written, but I have not a single place where actual distance matters. 

>  thanks for responding here. I feel like I'm still not quite understanding when the "nearest wins" rule gets applied.

Let me give a shot. 

* Nearest wins is probably best summarized as, direct dependencies of ancestors always win in that subgraph.
  * The first subgraph in which 2 versions of the same package appear determines what version gets selected.
* A more practical way of looking at it is that a
 downgrade will *only* happen if someone has explicitly added a top level package that has a lower version, at any point during the graph. 

Here's some examples: 

Simplest case of a downgrade is the following: 

![Simple Downgrade](https://user-images.githubusercontent.com/2878341/124966446-30d30d80-dfd8-11eb-9180-cf686de2f8ea.png)

* Project X, explicitly wants B 1.0, and because of direct dependencies of ancestors always win, when we look at B 2.0, the first time they are in the same subgraph is the complete graph here, and because B 1.0 is direct, it wins. 

Now say, someone *packaged* X and shipped X 1.0.0. 

Say I have a project in which I installed X 1.0.0. 

![SimpleDowngrade-Transferred](https://user-images.githubusercontent.com/2878341/124967289-177e9100-dfd9-11eb-9a9e-e7d27c2f98a4.png)

* B 2.0.0 and  B 1.0.0 first appear in X's graph. NuGet tries to preserve the user intention, so it selected 1.0.0. 

Now what if *another* subgraph has a B reference of 3.0.0.

Say you have the following:

![RejectedDowngrade](https://user-images.githubusercontent.com/2878341/124968071-0a15d680-dfda-11eb-9805-b5d8e7560920.png)

This is where the whole, cousins don't really look at the distance thing comes in. 
* For the X subgraph, B 1.0.0 is chosen, but is obv downgraded. 
* B 3.0.0 appears in a subgraph for the first time in the MyApp subgraph. Given that there's no direct dependency to B, here's where cousin dependency wins and the most compatible version is selected (in this case lowes)

Hope that helps. 

My goal is to rewrite the docs and I think we might have to rename the nearest wins rule because it's very confusing.

**Comment by madelson** [comment]
Thanks @nkolev92 those diagrams and explanations are super helpful.

I'm trying to think about **how to express this as a simplified algorithm** (for context, my underlying intent behind these questions is partly because I'm trying to replicate NuGet's restore algorithm in a piece of tooling I'm writing). Here's what I'm thinking so far:

```
(1) Draw out the full dependency graph. Whenever we encounter a package dependency range (e. g. A depends on B >= 1.0), we pick the lowest compatible version in that range. Project dependencies are nodes in the graph just like package dependencies (except they lack versions).

(2) Apply the "direct dependency of ancestor wins" rule the graph by pruning each subgraph which is superceded according to that rule.

(3) For any package with multiple versions remaining in the overall graph (cousin dependencies), select the highest (most compatible) version and prune all other versions.

(4) Detect any errors; basically we need to check whether the globally selected version of each package is compliant with the dependency version ranges for all other selected versions. Step 2 can result in invalid downgrades of packages, while step 3 can result in invalid upgrades of packages if there are version ranges with upper bounds (e. g. in your example if X depended on B [1, 3) then selecting B 3.0 would be an error).
```

Does this seem right? 

One area that feels a bit vague is step 3 because it feels like we could get different outcomes depending on what order we processed packages in. For example, imagine if our graph after step 2 was this:
```
MyApp -> X 1.0 -> A 1.0 -> B 2.0
             -> Y 1.0 -> A 2.0
             -> Z 1.0 -> B 1.0
```
If we resolved package A first we'd end up pruning the A 1.0 subgraph and keeping B 1.0. However if we consider B first then we'll pick B 2.0 (unless the algorithm has some way of revisiting the previous resolution?). What is it supposed to do here?

**Comment by nkolev92** [comment]
The algorithm is supposed to pick A 2.0 and B 1.0. 

Firstly, all packages are detected.
Then direct dependencies of ancestor wins is applied and nothing happens because there's no direct deps. 

Finally the graph is walked in a BFS fashion, and we will do multiple passes in order to resolve all conflicts.
X, Y & Z are all selected, and then we come to A, and when checking A 1.0, we already know *about* 2.0, so A 1.0 will be rejected because it's not the best version. 
A 1.0 gets rejected, then we do A 2.0, which will get accepted because it's the best version.
At the end of that the 2nd level pass, B is going to be treated as ambiguous, because we still see a different version of it lower in the graph.

In the next pass, we know A 1.0 was rejected, so B 2.0 gets rejected as well, so B 1.0.0 becomes unambiguous. 

You can see the code in https://github.com/NuGet/NuGet.Client/blob/f04b570e65af9f7828f01968c1efdf42e8f317d7/src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphOperations.cs#L26-L37.

**Comment by gaborposz** [comment]
@nkolev92: Do I see well that your second example is exactly the same scenario that I've tested?
(See above in the issue's description.)

You wrote:
> B 2.0.0 and B 1.0.0 first appear in X's graph. NuGet tries to preserve the user intention, so it selected 1.0.0.

For me version 2.0.0 was selected, not 1.0.0.
(The package names and versions were different in my example, but the point was the same.)

I'm confused, is there a difference that I haven't noticed?
Have you tried it in practice, e.g. with a local NuGet feed, like me?

**Comment by nkolev92** [comment]
Yes, I used tests to confirm the behavior. 

The 3 tests are available here: https://github.com/NuGet/NuGet.Client/blob/ed04716852723771d9ce95ad2ea0c8c6ac31ce54/test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/RemoteDependencyWalkerTests.cs#L1813-L1912

@madelson Here's an easy way to validate NuGet' behavior through tests. 

This is something I cooked up locally:
> C:\Code\Temp\NDR\MyApp\MyApp.csproj : error NU1605: Detected package downgrade: B from 2.0.0 to 1.0.0. Reference the package directly from the project to select a different version.
C:\Code\Temp\NDR\MyApp\MyApp.csproj : error NU1605:  MyApp -> X 1.0.0 -> A 1.0.0 -> B (>= 2.0.0)
C:\Code\Temp\NDR\MyApp\MyApp.csproj : error NU1605:  MyApp -> X 1.0.0 -> B (>= 1.0.0)

**Comment by gaborposz** [comment]
@nkolev92: Ok, it still gives me headache when I'm trying to understand it, but maybe now I'm closer :)

First of all, I was wrong, your example and my example are different.

This was yours:
![Issue2434_nkolev92s_example](https://user-images.githubusercontent.com/47426565/125477751-c5a0ff90-be8f-4c65-a2e3-c8b57ffb4c92.png)

And this is mine:
![Issue2434_gabors_example](https://user-images.githubusercontent.com/47426565/125477769-fabfd529-d4fd-4fdd-8543-d8c36b00a493.png)

In your case the B 2.0.0 package (greyish) was thrown out becuase of the "nearest wins" rule, while in my case the D 1.0.0 package (greyish) was thrown out because of the "cusine dependencies" rule.

So if I interpret it well, then the "nearest wins" rule is only applied if there is a junction in the tree, and only on the level of the junction. 

By "junction" and "level of juction" I mean the following:

![Issue2434_nkolev92s_example_with_explanation](https://user-images.githubusercontent.com/47426565/125486542-61fd520d-7d37-4bca-867f-4502201e6548.png)
Here the "nearest wins" rule was used, because B also appeared on lower levels of the graph.


![Issue2434_gabors_example_with_explanation](https://user-images.githubusercontent.com/47426565/125486564-e3dc7386-f59e-41a8-aa18-e5cdd4f8931d.png)
Here the "nearest wins" rule was not used, because B (and A) only appeared once in the graph.
Pacakage D appeared more times in the graph, but that was not on the "level of the juction", hence it was resolved by the "cousin dependencies" rule. 


Is it correct?

**Comment by nkolev92** [comment]
Yep, that seems right.

**Comment by madelson** [comment]
It seems like we're getting close to a concise description of how this works that could replace and clarify the existing docs!
