### ISSUE TITLE
Not helpful, it is a simple hello world case.

### ISSUE THREAD

**Issue by SwissMaWi** [NuGet/docs.microsoft.com-nuget#2482]
As very common these days documentation by Microsoft is getting worse and worse. This process is unusable for practical work since it does not produce any dependency information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8beb111-7b49-2fbe-eeb5-e485b6515ef2
* Version Independent ID: 22535840-0a27-797e-ebc8-5dbe447156d2
* Content: [Create and publish a .NET Framework NuGet package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by zivkan** [comment]
84% of all packages on nuget.org have only `lib/*` assets, none others. This guide is sufficient to create a similar package. Furthermore this is a quickstart guide, not an in-depth reference.

Having said that, I strongly recommend that even if you need to create a .NET Framework package, that you start with the [.NET Standard (Visual Studio) quickstart](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli), and re-target the project from netstandard to .net framework.  The SDK style project experience is much better than the non-SDK style project experience. In particular, SDK style projects make it trivial to multi-target your project/package for multiple TargetFrameworks, whereas non-SDK style projects require multiple csproj files and a much more complex nuspec file. However, the .NET Standard package quickstart also creates a package that only contain `lib/*` assets.

I just think it's unfair to claim that the page is unhelpful and "unusable for practical work" when it satisfies 84% of all packages on nuget.org.


If you could tell us what else your package needs, we can point you to existing documentation, or know what gaps you think the documentation has. I don't know how I could improve these docs based on your feedback so far.

**Comment by SwissMaWi** [comment]
Sorry... your comment does not seem to have anything to do with the issue. I am just telling that the help from Microsoft is poor, as it is symptomatic. I have started programming with the original IBM PC in the 80's of the last century. At that time, documentation was 100% complete, clear and correct with extensive examples. The documentation of Microsoft in this case on how to produce a .Net Framework NuGet package is at best mediocre. Examples should explore ALL options. In a practical environment packages do have dependencies. And the example is simply omitting that fact leaving the interested reader with only the basics which are enough for a hello world application but not enough for serious application development.

**Comment by zivkan** [comment]
> your comment does not seem to have anything to do with the issue

The title of this issue is "Not helpful, it is a simple hello world case", you wrote 20 words on how you think the docs are unusable, and 8 words about dependencies. This made me believe your issue was about the docs in general, not about dependencies. Pointing out that this doc page should be sufficient for 84% of packages on nuget.org seems to be relevant in countering your claim that the doc is unworkable for practical work, the topic of your feedback. If you intended to give feedback that you want dependency information on the page, then a more clear title, and having the majority of your feedback on that topic, rather than a minor point at the end would have been much more clear to me. I'm still unclear what the desired outcome of your feedback is.

On the topic of dependencies, you shouldn't need to do anything special to get dependencies listed in your package. Install the dependencies in your project using the Package Manager UI, write code to use those packages, just like you would if you're not creating a package.  When you pack the project, the project's installed packages become your package's dependencies.

It's not clear to me if this is the information you want to be added to the specific docs page, or if you're giving feedback that you think this specific docs page would still be insufficient quality, or if you're talking about all the docs as a whole.

If you're referring to this docs page specifically, we get feedback from a number of sources, and I'm not directly involved in that, but my understanding is that young students in particular find long docs intimidating and causes them to be more likely to look for alternatives. So, this docs page becoming exhaustive for all options will be a barrier for people getting started with .NET. Different people have different learning styles, and I don't want to exclude them. We can have exhaustive docs elsewhere, for example the references section, not a page that explicitly says "quickstart".

The docs as a whole being a problem is something I agree with. The NuGet team doesn't have dedicated technical writers who work full time on docs, unlike other teams. Simultaneously I feel like we're under far more pressure to deliver bug fixes and new features. We add reference docs when new features are implemented, but I'm not sure how managers expect the docs to have a significant overhaul.
