### ISSUE TITLE
NU1201 documentation - confusing ProjectA vs ProjectB

### ISSUE THREAD

**Issue by NorbertNemec** [NuGet/docs.microsoft.com-nuget#2495]
On the documentation page on NU1201, the first example message mentions `ProjectA` twice while the second example message mentions `ProjectB` twice. Then the explanation for the second example mentions both project without ever defining `ProjectA`

Indeed the error message mentions the depending project twice, without stating the depended-on project at all. Possibly the real bug is in that error message itself? In any case, the documentation is completely confusing on its own.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64341f8e-3f83-a6f2-f100-5bab3c6e6c77
* Version Independent ID: bf00b11d-1dcc-45c4-fbf8-929305fe49c6
* Content: [NuGet Error NU1201](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1201)
* Content Source: [docs/reference/errors-and-warnings/NU1201.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1201.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
I read through the error documentation and I'm not sure if I understand the issue here.

The first example mentions project A twice because it is saying that project A **is not compatible** with what project B provides. It then says project A **is compatible** with a specific TFM.

The same applies for the second scenario.

Can you please help us understand the confusion further? I know you've probably forgot about this issue since it's been awhile, but I'd love to understand more.

If it would make this easier to understand, perhaps we need to be explicit about **where** the incompatible TFMs are coming from.

**Comment by nkolev92** [comment]
I think the biggest issue is that the current project is not obvious in the docs: 

If you look at a practical error here's what you get

You'd get 

```console
C:\Code\Temp\NU1201-Real\Parent\Parent.csproj : error NU1201: Project Child is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Project Child supports: net6.0 (.NETCoreApp,Version=v6.0) [C:\Code\Temp\NU1201-Real\NU1201-Real.sln]
```

Note the context on the left side at the beginning of the message about the `current project`. 

It seems like in the 2nd example, it is assumed that `ProjectA` is assumed to be the current project, but that's not true in the first example.
