### ISSUE TITLE
Very unclear where the readme.md should be stored for the packager to find it.

### ISSUE THREAD

**Issue by WithUnity** [NuGet/docs.microsoft.com-nuget#2537]
I have this error on a net 5.0 project and this page does not give me a clue as to where the README.md should be stored for the packager to find it. or what else I am doing wrong if I am doing something wrong.

Github by default creates  README.md in $(SolutionDir).  So I left it there.

Adding 
```
  <PropertyGroup>
      <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>
and
      ...
  <ItemGroup>
      <None Include="readme.md" Pack="true" PackagePath=""/>
  </ItemGroup>
```
or 
```
  <ItemGroup>
      <None Include="docs\readme.md" Pack="true" PackagePath=""/>
  </ItemGroup>
```
Using this default location does not work. I get  error NU5039: The readme file 'README.md' does not exist in the package

I then tried copying the file to $(ProjectDir); $(TargetDir); $(ProjectDir)\docs; $(TargetDir)\docs, all without success.
I have also tried adding it to bin\release and bin\release\docs, also without success.
$(TargetDir) = bin\release\net5.0

So where should this file be in the solution/project hierarchy for the packager to find it and where should it be copied to assuming it should end up in the $(TargetDir)?

I also want to know how can I ensure other documentation files are also copied to the package documentation.
e.g. the XML documentation; security.MD; and any other MD files that are bigger than 8 kB My generated document is nearer 60kB.

Lastly, I want to add a Summary to the project but this is only available if I add a .nuspec file.
So I added a .nuspec file to the project. 
If you have metadata in the project and the .nuspec file which takes precedence?.
Apparently from my experiments, the .nuspec file is reading files from the $(ProjectDir) I get "error NU5019" if I put a path not relative to $(ProjectDir) in the files section.

I tried doing the same thing with a .NETframework 4 library and I could not find an option to create a package at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85304791-b8cd-f76a-2750-8d2389147b41
* Version Independent ID: 218b3987-a8b2-de82-e490-8c943529ff19
* Content: [NuGet Error NU5039](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5039)
* Content Source: [docs/reference/errors-and-warnings/NU5039.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU5039.md)
* Product: **nuget**
* GitHub Login: @chgill-MSFT
* Microsoft Alias: **chgill**

**Comment by zivkan** [comment]
> this page does not give me a clue as to where the README.md should be stored for the packager to find it.

Different people/teams/projects have different requirements, so there is no "one size fits all" solution. Put it wherever it makes sense for you.

> Github by default creates README.md in $(SolutionDir). So I left it there.

Assuming you are putting your solution (`.sln` file) in the repository root, then yes, but some people put solutions under a `src/` folder or somewhere else.

Anyway, speaking from my own personal opinion, not the whole team, the repository readme often has details like instructions on how to build, a contribution guide, coding standards (for modifying the library, not using it in your own project), code of conduct, and more. These are all topics that only make sense to someone looking at the source code for your library, not nuget.org or someone having installed the package into their own project.  Therefore, I personally imagine that the most common configuration is to have two readmes, one for the repo, another for the package.

> Using this default location does not work.

MSBuild's documentation on Items, [specifically the "Create items in a project file" section](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2019#create-items-in-a-project-file) says:

* The Include attribute is a path that is interpreted relative to the project file's folder, $(MSBuildProjectPath), even if the item is in an imported file such as a .targets file.

Therefore in your csproj you can use `<None Include="../readme.md" .... />`.

> So where should this file be in the solution/project hierarchy for the packager to find it and where should it be copied to assuming it should end up in the $(TargetDir)?

Files don't need to be copied to the bin directory to be put into the package. Build and Pack are two different MSBuild targets, with different goals.

> I also want to know how can I ensure other documentation files are also copied to the package documentation.

Add as many `<None Include="???" Pack="true" PackagePath="???" />` elements as you need.  Note however that NuGet only supports a single readme file. Your package consumers will only discover these additional files by looking at your package directory, NuGet's own tooling won't show them links, and the files won't be visible on nuget.org.

> So I added a .nuspec file to the project.

As per [our docs](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec-file), you need to set some properties in addition to creating the nuspec file.  However note that if you use a nuspec file, then NuGet doesn't generate any of the package content from MSBuild properties and items. This means your nuspec needs to not only contain the summary, but also the package id, version, description (yes, there are separate summary and description fields, and I don't know why), license, readme, all the files that should be included in the package, everything.

> I tried doing the same thing with a .NETframework 4 library and I could not find an option to create a package at all.

SDK style projects can target the .NET Framework. I don't know why Visual Studio doesn't provide the target framework monikers in the dropdown, but you can hand edit the csproj and change the TargetFramework or TargetFrameworks element to contain `net48`, and now it targets .NET Framework 4.8. This allows you to keep using the dotnet cli and all of the other improved tooling that SDK style projects provide.


I'm leaving this open so that our PMs, such as @chgill-MSFT, can consider whether we need to improve the docs to make any of this clearer.
