### ISSUE TITLE
Document which schema are valid for nuspec and what are the differences

### ISSUE THREAD

**Issue by nils-a** [NuGet/docs.microsoft.com-nuget#2540]
Every example on that page has `http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd` set as `xmlns`.
However, it seems that this is not the only valid schema.

The page currently lacks a documentation which schemas are available and which tags/elements are valid in which version.
In my case I am wondering what the correct schema would be to use the `readme` element.
(There is a reference to the current development version of the schema at https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd but there is no indication on how to "use" that.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
@nils-a We have a section for README here:

https://docs.microsoft.com/en-us/nuget/reference/nuspec#readme

This should include version information as well for what is valid w/ examples. Let us know if anything else should be changed.

**Comment by nils-a** [comment]
@JonDouglas thanks for answering. What I am missing here is the information of what exactly should I put in `xmlns=...` to have `readme` appear as a valid tag?

The link you provided states "*NuGet 5.10.0 preview 2*" - however, that's the NuGet version and not the schema version. The top of that page refers to [nuspec.xsd](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd) - which I did find (and linked) but what I can not find are the available, published versions of that schema.
*NuGet 5.10.0* was somewhere in March 2021, so I guess my question is: Is there a `http://schemas.microsoft.com/packaging/2021/03/nuspec.xsd`? Are valid schema versions (and the correlation to NuGet versions) documented somewhere?

I would happily provide a PR to the page above (and probably https://docs.microsoft.com/en-us/nuget/reference/nuspec, too) if someone could point me to the information.

**Comment by zivkan** [comment]
@nils-a to the best of my knowledge, the NuGet team has never published a XSD schema for nuspec files.

The implementation of NuGet's nuspec reader is that it iterates all xmlns uris that were ever allowed with the same schema, trying to find one that works. Therefore, as long as you're using a new enough version of NuGet (whether it's `dotnet pack`, or `nuget.exe pack`), if the `readme` element is allowed, it will be allowed for any xmlns.

> However, it seems that this is not the only valid schema.

What tool is giving you this error?  If it's some kind of intellisense or code complete, it must be using a schema that the NuGet team doesn't maintain, because as I said, I don't believe NuGet has ever published a usable xsd file. We certainly haven't since I joined the team.

**Comment by nils-a** [comment]
@zivkan 
> to the best of my knowledge, the NuGet team has never published a XSD schema for nuspec files.

From https://learn.microsoft.com/en-us/nuget/reference/nuspec:
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/349188/dbedd545-9314-46d5-97ff-03750473b495)

The link points to https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd

All of that, I already stated in https://github.com/NuGet/docs.microsoft.com-nuget/issues/2540#issuecomment-1026529636

> What tool is giving you this error?

VSCode

**Comment by zivkan** [comment]
I'm not sure who added that link to the docs. The source for our docs was modified during some kind of migration, so the best I can find is that it was added to the docs in 2016: https://github.com/NuGet/docs.microsoft.com-nuget/pull/3/files#diff-b06d4e9359447aab89247b8eb8fb1661e2c4531219f0780183de2f7cd2339cb7

However, nuspec.xsd in the NuGet repo was modified to be invalid syntactically since 2011: https://github.com/NuGet/NuGet2/commit/df7b3e9f9d2a79ec0d343e31817b8f7ac90e4055#diff-3ce29670fe9e803e98d31e594c8ebf83c179c51b9776c95f7d569216ee326d17


So, to kind of answer the original question, NuGet.Client stopped changing the namespace URL when adding new fields to the nuspec. NuGet pack also uses the same nuspec.xsd for all namespaces it checks, so as long as you're using a version of nuget.exe or the .NET SDK that knows about the readme element, then it doesn't matter which nuspec namespace you use, NuGet will accept it.

Here are the list of namespaces URLs that NuGet accepts: https://github.com/NuGet/NuGet.Client/blob/e7c0ef3fe9ebb65a2fa7b960c6ee760521d66e08/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L23-L50

However, I maintain that since 2011 NuGet has not published an xsd that other tooling can use for automatic schema validation.  Although the namespace URL uses https://schemas.microsoft.com, I don't believe that the schema was ever published to that domain.

All this means that we have poor tooling experience for XML editors who want to provide autocomplete or syntax validation, because we don't have a schema file for them to use. Plus, the same namespace has different fields depending on the NuGet version, which is a violation of what namespaces are supposed to be. If VSCode is providing you with an editor experience for other nuspec fields, just not the readme element, then I have no idea where it's getting the schema from.

**Comment by nils-a** [comment]
So, the best next step would be to at least remove that note from the docs, better still to add some nice phrasing around "there is no schema"?

**Comment by nils-a** [comment]
A PR was created and is still open - it would be a shame to close this isse now.
