### ISSUE TITLE
packageManagement.format bool type conflicts 0 1 values

### ISSUE THREAD

**Issue by ite-klass** [NuGet/docs.microsoft.com-nuget#2640]
`packageManagement` `format` says it is a Boolean, but then documents values `0` and `1`.

I assume the type declaration is wrong? That the type is an int?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagemanagement-section)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
I don't believe this is a type declaration being wrong. I believe it was an implementation detail that was missed as XML allows arbitrary values and bool can be expressed with both true, false, 0, and 1.

https://stackoverflow.com/a/49161729

Because this was intentional and the product is actually designed this way, I don't believe there's an issue here we can address in docs.
