### ISSUE TITLE
Should we add other possible solutions here?

### ISSUE THREAD

**Issue by mairaw** [NuGet/docs.microsoft.com-nuget#2642]
On the dotnet/core repo, I've seen people run into the issue of missing sources on Nuget.config.
e.g. https://github.com/dotnet/core/issues/6203

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b306fb-72a2-e479-b745-a89b0095764d
* Version Independent ID: c0b1a587-20c1-c885-a9f8-1cb7340f1d51
* Content: [NuGet Error NU1100](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100)
* Content Source: [docs/reference/errors-and-warnings/NU1100.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1100.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
This is more of a downstream issue where projects like chocolatey were creating empty nuget.config files to workaround an issue that has since been resolved in NuGet.

With that said, I'm not sure how to improve this error message or code given the solution already asks the user to check packages exist on the defined package sources. Any ideas?

**Comment by mairaw** [comment]
Maybe clarify where the package sources can be found or give example? It wasn't clear to me what the generic error description meant until I went to research about the issue to help customers.

**Comment by nkolev92** [comment]
I imagine this is restore? 

Restore prints all the sources and configs being used in a summary. 

```
      NuGet Config files used:
      C:\Code\NuGet.Client\NuGet.Config
      C:\Code\NuGet.Config
      C:\Users\Roki2\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.FallbackLocation.config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
      C:\Program Files (x86)\NuGet\Config\Xamarin.Offline.config

  Feeds used:
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json
      https://pkgs.dev.azure.com/dnceng/public/_packaging/myget-legacy%40Local/nuget/v3/index.json
      https://pkgs.dev.azure.com/dnceng/public/_packaging/nuget-build/nuget/v3/index.json
      https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json
      https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json
  All projects are up-to-date for restore.
Done Building Project "C:\Code\NuGet.Client\NuGet-Src-Commandline.slnf" (Restore target(s)).
```

It's likely that the verbosity is the issue here. 
The config files used and feeds used messages are normal verbosity, while the rest is minimal. 

I think adding these details in the error message would make the messages significantly longer than they need to be. 

However, i think adding more examples in the docs is an easy win.

**Comment by mairaw** [comment]
Yes, I believe it was during a restore operation after dotnet new in the example I gave above.
