### ISSUE TITLE
NuGet Client SDK - Connecting to a private NuGet feed through code

### ISSUE THREAD

**Issue by kalyani1217** [NuGet/docs.microsoft.com-nuget#2673]
I'm using a private NuGet feed through Azure DevOps.
To see information about a public NuGet package from code, one simply has to follow the documentation [here](https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#work-with-authenticated-feeds). In particular:

```
var logger = NullLogger.Instance;
var cancellationToken = CancellationToken.None;
var tokenName = "mypersonalaccesstokenName";
var personalaccesstoken = "mypersonalaccesstoken";
var cache = new SourceCacheContext();    
var source = new PackageSource("*my feed*/nuget/v3/index.json");
source.Credentials = new PackageSourceCredential("*my feed*/nuget/v3/index.json", tokenName, personalaccesstoken , false, null);

var repository = Repository.Factory.GetCoreV3(source);
var resource = await repository.GetResourceAsync<PackageMetadataResource>();

FindPackageByIdResource resource = await repository.GetResourceAsync<FindPackageByIdResource>();

            IEnumerable<NuGetVersion> versions = await resource.GetAllVersionsAsync(
                "MyPackageId",
                cache,
                logger,
                cancellationToken);

```
At line "var resource = await repository.GetResourceAsync<PackageMetadataResource>();" I'm seeing "unable to load the service index for source *my feed*/nuget/v3/index.json" exception.
Any suggestions to work the above code so that I can connect to Azure DevOps NuGet feed to get my package versions.

**Comment by zivkan** [comment]
Did you try implementing a logger, rather than just using the `NullLogger`? For example:

```csharp
class MyLogger : NuGet.Common.LoggerBase
{
    public override void Log(ILogMessage message)
    {
        Console.WriteLine("("+message.Level+") " +message.Message);
    }

    public override Task LogAsync(ILogMessage message)
    {
        Log(message);
        return Task.CompletedTask;
    }
}
```

I tried this, copying your code, and this provided me with the follow error:

> Unhandled exception. NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://pkgs.dev.azure.com/devdiv/_packaging/MicroBuildToolset/nuget/v3/index.json.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The parameter is incorrect
   at System.Security.Cryptography.ProtectedData.ProtectOrUnprotect(Byte[] inputData, Byte[] optionalEntropy, DataProtectionScope scope, Boolean protect)
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at NuGet.Configuration.EncryptionUtility.DecryptString(String encryptedString)
   at NuGet.Configuration.PackageSourceCredential.get_Password()
   at NuGet.Configuration.PackageSourceCredential.ToICredentials()

We can see from the stack trace that it's trying to `EncryptionUtility.DecryptString`. Looking at the docs that you linked it, it has this:

```csharp
    Credentials = new PackageSourceCredential(
        source: sourceUri,
        username: "myUsername",
        passwordText: "myVerySecretPassword",
        isPasswordClearText: true,
        validAuthenticationTypesText: null)
```

which you changed to this:

```csharp
source.Credentials = new PackageSourceCredential("*my feed*/nuget/v3/index.json", tokenName, personalaccesstoken , false, null);
```

Notice that the 4th parameter, the `isPasswordClearText` boolean, was changed from `true` in the sample, to `false` in your code.

Unless the string you provided in `personalaccesstoken` was encrypted with DPAPI (`ProectedData.Proect(...)`), you need to pass `true` for this parameter.
