### ISSUE TITLE
Não é possível carregar o índice de serviço

### ISSUE THREAD

**Issue by pablim** [NuGet/docs.microsoft.com-nuget#2696]
I'm in a linux enviroment

/usr/share/dotnet/sdk/6.0.201/NuGet.targets(130,5): error : Não é possível carregar o índice de serviço para a origem https://sysdam-nb.pkgs.visualstudio.com/Sysdam/_packaging/Pacotes/nuget/v3/index.json. [/home/pablo/Solveware/SysgeoWebApi/SysGeo/SysGeo/SysGeo.csproj]
/usr/share/dotnet/sdk/6.0.201/NuGet.targets(130,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/home/pablo/Solveware/SysgeoWebApi/SysGeo/SysGeo/SysGeo.csproj]

Ocorreu uma falha no build. Corrija os erros de build e execute novamente.

**Comment by nkolev92** [comment]
Hey @pablim 

Not sure what this issue is supposed to be about. 

If you are working with private feeds on linux environments, please refer tohttps://github.com/microsoft/artifacts-credprovider. 



https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds#dotnetexe-and-v2-credential-providers
