### ISSUE TITLE
Incorrect or Inaccurate Description of PackageReference Properties

### ISSUE THREAD

**Issue by fiercekittenz** [NuGet/docs.microsoft.com-nuget#2698]
We have a rather large solution here at work (over 250 projects) and were running into some issues with the PackageReference properties/flags to try to control what they were being used for in order to avoid multiple copies of DLLs being thrown into our /bin/ directory. One thing about our solution that may be different from the expected output pattern for C# projects is that we put everything into a single /bin/ and don't use dotnet publish. 

We've found the following problems with the documentation on <IncludeAssets> and <PrivateAssets> that could use clarification or corrections as one of our senior engineers lost a day trying to figure out why they weren't working as documented:

- Build and runtime flags appear to be reversed. Build actually copies the libraries into the folder and runtime appears to update the .props and .targets flags in the deps.json file.
- This means that IncludeAssets needs to be runtime;compile and PrivateAssets needs to be build. Naming does not appear to be aligned with the description in the documentation. IncludeAssets should be named InheritedAssets and PrivateAssets should be LocalAssets or something more appropriate to what it's actually doing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference in project files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
Thanks for filing this issue. 
A couple of questions.

> Build and runtime flags appear to be reversed. Build actually copies the libraries into the folder 

That doesn't sound right. 
The `build` asset group has to do with the `props` and `targets` being included at build time. 
deps.json is something that's totally independent of the `build` asset type for PackageReference. 

> runtime appears to update the .props and .targets flags in the deps.json file.

Can you elaborate on this? I'm not sure how to intepret it. deps.json is an intermediate and not an msbuild file, https://github.com/dotnet/sdk/blob/main/documentation/specs/runtime-configuration-file.md. 

> This means that IncludeAssets needs to be runtime;compile 

I'd love to see an example demonstrating why 
and PrivateAssets needs to be build. Naming does not appear to be aligned with the description in the documentation. IncludeAssets should be named InheritedAssets and PrivateAssets should be LocalAssets or something more appropriate to what it's actually doing.

**Comment by nkolev92** [comment]
Thanks for filing this issue. 
A couple of questions.

> Build and runtime flags appear to be reversed. Build actually copies the libraries into the folder 

That doesn't sound right. 
The `build` asset group has to do with the `props` and `targets` being included at build time. 
deps.json is something that's totally independent of the `build` asset type for PackageReference. 

> runtime appears to update the .props and .targets flags in the deps.json file.

Can you elaborate on this? I'm not sure how to intepret it. deps.json is an intermediate and not an msbuild file, https://github.com/dotnet/sdk/blob/main/documentation/specs/runtime-configuration-file.md. 

> This means that IncludeAssets needs to be runtime;compile and PrivateAssets needs to be build

I'd love to see an example here. I'm not sure it's quite correct. 


> Naming does not appear to be aligned with the description in the documentation. IncludeAssets should be named InheritedAssets and PrivateAssets should be LocalAssets or something more appropriate to what it's actually doing.

- IncludeAssets are the asset types that are going to be used from that package. I think the name is appropriate here. The description in the docs is `These assets will be consumed`, which I think is equivalent.

- PrivateAssets are the asset types that around going to be consumed by the current project only, thus staying private to the project specifying it. The description in docs is `These assets will be consumed but won't flow to the parent project` which I think is equivalent.

There's definitely some overloaded terms such as `build`, maybe that's the root cause of the confusion.
