### ISSUE TITLE
Document the package structure of the global packages folder and the differences from the packages.config repository path. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#2771]
The structures are different and these 2 should *never* point to the same location.

**Comment by r0bfr** [comment]
When parity _is_ desired (i.e. one wants to ensure that all `packages.config` and all `<PackageReference/>` downloading share the exact same cache), is there any reason why a new key couldn't be added to the `nuget.config` schema that tells the V2 codepath to use the same folder structure as the V3 codepath?

Since `<PackageReference/>` continues to be unsupported for C++, it would be nice to create a way for VCXPROJ and CSPROJ projects to live in harmony in the same repository.  The same package used by each of these Project types should only have to be downloaded a single time.

As an additional use case, consider the scenario where (for development purposes), a developer would like to "patch" the contents of a NuGet package that's being used by the projects in their repository (their team also owns development of that package).  Rather than having to rebuild new NuGet packages each time a patch is necessary, they would like to simply use a script to overwrite the contents of a folder in the downloaded cache copy of the package.  If the V2 and V3 codepaths were sharing the same cache, this would ensure that a single folder needs to be overwritten each time a patch is needed.  With things working the way they do now, however, one patch is needed for the V2 folder (created by VCXPROJ projects using the package), and another patch is needed for the V3 folder (created by CSPROJ projects using the package).

**Comment by zivkan** [comment]
@r0bfr as per our recently published triage policy: https://github.com/NuGet/Home/blob/dev/Issue-Triage-Policy.md

Please look for an existing issue and upvote it (I didn't read [this issue](https://github.com/NuGet/Home/issues/9563) carefully, but at a glance it appears to be about the same topic), and if you can't find a suitable one, [create a feature request](https://github.com/NuGet/Home/issues/new?assignees=&labels=Type%3AFeature%2CTriage%3AUntriaged&template=FEATURE.yml&title=%5BFeature%5D%3A+). If enough people upvote the request, then the work will be investigated/prioritized.
