### ISSUE TITLE
Add a guide to create build extensions and/or source packages

### ISSUE THREAD

**Issue by chkoella** [NuGet/docs.microsoft.com-nuget#2938]
Please add a guide on how to create a build extension packages or (source code) content packages.
I had to search several documentations, forums and github issues for about a whole day just to create a small nuget that contains a props file and a shared source file (but no DLL).

What especially bothered me was the NU5017 error because I had accidentally set <IncludeSymbols>true</IncludeSymbols>. The error is very confusing because the package gets created but the symbol package fails. (This issue finally helped me: https://github.com/NuGet/Home/issues/10372)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bca41d96-58d7-6586-5b66-39265853acc2
* Version Independent ID: a6d86de4-d74c-9274-b900-4922f833b6a7
* Content: [Overview and workflow of creating NuGet packages](https://learn.microsoft.com/en-us/nuget/create-packages/overview-and-workflow)
* Content Source: [docs/create-packages/Overview-and-Workflow.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/Overview-and-Workflow.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by baronfel** [comment]
By 'build extensions', do you mean shipping MSBuild properties and targets? If so, you can find documentation on that process over on the MSBuild docs pages. Specifically [this portion of the document](https://learn.microsoft.com/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022#package-the-task-for-distribution) talks about packaging MSBuild extensions, and also takes into account how to multi-target them so that they work in Visual Studio (msbuild.exe) as well as .NET SDK (dotnet build) scenarios.
