### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by gaharlan** [NuGet/docs.microsoft.com-nuget#2952]
Installed the required NuGet packages Packaging and Protocol, attempted to try the examples none work.
none of the references for the objects exist in the NuGet dll's
NuGet.Protocol.Core.Types is depreciated.  So what to use?
is this also the location for Repository.Factory?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb17b741-1635-af19-e74b-d9921b0bd1ab
* Version Independent ID: 740217ba-335d-6401-64a1-d2f5d8e74f82
* Content: [NuGet Client SDK](https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk)
* Content Source: [docs/reference/NuGet-Client-SDK.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/NuGet-Client-SDK.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by zivkan** [comment]
@gaharlan I tried creating a new .NET 6 console app in VS, copy-pasted the first sample (list Newtonsoft.Json package versions) into Program.cs, used the lightbulb menu on the `SourceCacheContext` line to install NuGet.Protocol (roslyn knew which package this type comes from, so I didn't need to install the package myself), then used the lightbulb menu on each line with unresolved types to add using statements for the relevant type. The sample then ran successfully.

The full set of usings I ended up with are (keeping in mind the project template has default usings):

```cs
using NuGet.Common;
using NuGet.Protocol;
using NuGet.Protocol.Core.Types;
using NuGet.Versioning;
```

Now that C# has "top level programs", we can probably change the samples to use this syntax, and therefore include the using statements in each sample without needing a class and method definition, that previously made code snippets much longer. But it's a trade off between short samples that show the API vs longer self-contained samples that can be copy pasted, but has more boilerplate.

> NuGet.Protocol.Core.Types is depreciated. So what to use?
> is this also the location for Repository.Factory?

The [note at the NuGet.Protocol section of the docs](https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk#nugetprotocol) says:

> Repository.Factory is defined in the NuGet.Protocol.Core.Types namespace, and the GetCoreV3 method is an extension method defined in the NuGet.Protocol namespace. Therefore, you will need to add using statements for both namespaces.

Years ago, the code in NuGet.Protocol.Core.Types was moved to NuGet.Protocol, and at first the package contained only type forwarding declarations, to make the core binary compatible. After a while, we stopped creating new versions of the package (and marked it as deprecated on nuget.org), as we expect anyone using it to have migrated to NuGet.Protocol by that time. However, because of backwards compatibility concerns, the namespace remained the same, in the different assembly.
