### ISSUE TITLE
Update URL samples in registration-base-url-resource docs

### ISSUE THREAD

**Issue by taori** [NuGet/docs.microsoft.com-nuget#3086]
### NuGet Product(s) Affected

Other/NA

### Current Behavior

None of the samples for https://learn.microsoft.com/en-us/nuget/api/registration-base-url-resource work.
Quering a package like this: https://github.com/taori/NugetUnlister/blob/master/src/NugetUnlister/Helpers/PackageHelper.cs does not appear to work anymore either.

I am getting this error now:
![grafik](https://github.com/NuGet/Home/assets/5545184/2c7ba107-e638-45e0-966c-aefb9b358155)

### Desired Behavior

It would be good if package querying kept working

**Comment by joelverhagen** [comment]
I am on the NuGet.org team. I can confirm @zivkan's response. The examples are correct since they all have lowercase package IDs and versions. Note that the examples do NOT use real base URLs which is why, if requested, they return an HTTP 4XX. The part that is correct is that the ID and version samples are lowercased. The base URL must be fetched from the service index as described in the documentation.

If you see some other error in the sample, could you please clarify what you mean?

The reason for the difference is as @zivkan says. We have multiple CDN providers and their behaviors have some minor, nuanced differences. In this case, it's essential for client software to adhere to the documented protocol and lowercase package ID and version strings before concatenating them into URL strings.

**Comment by taori** [comment]
Yesterday:
not tested: https://api.nuget.org/v3-flatcontainer/amusoft.ui.wpf/index.json
failed: https://api.nuget.org/v3-flatcontainer/Amusoft.UI.WPF/index.json

Today:
works: https://api.nuget.org/v3-flatcontainer/amusoft.ui.wpf/index.json
works: https://api.nuget.org/v3-flatcontainer/Amusoft.UI.WPF/index.json

Could it be that it was perhaps just a service degredation yesterday? Or perhaps there was a code change that now lowercases the package name?
