### ISSUE TITLE
Cannot fix NuGet package(s) are missing on this computer. 

### ISSUE THREAD

**Issue by miraboreasumr** [NuGet/docs.microsoft.com-nuget#3093]
Hi, I tried to set the settings in my Visual Studio like this,
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/32586051/c3605e78-0268-4a12-90ec-4b24a2167574)

but it still says
The missing file is packages\pthreads.redist.2.9.1.4\build\native\pthreads.redist.targets.
Thanks

**Comment by zivkan** [comment]
@miraboreasumr the most common cause of this problem is either changing the directory structure of projects, or adding a project to a second solution, where the relative path of that solution is different to the first solution the project correctly works in.

If you look at the project file in a text editor, you'll find the missing file referenced, and the relative path it expects the package to be in. You should also find a `packages` subdirectory in the directory that your `.sln` file is in. If they're not the same, the condition you see in your project file that reports the error, will report the error.

This can often be resolved by running `Update-Package -Reinstall` in the Package Manager Console.  But as described above, if this project is in more than one solution, "fixing" it for one solution will break it for a different solution.

Since this is in the docs repo, I'm trying to think where this could be documented that will be easy to find. At the same time, this issue only exists for projects using packages.config, which is becoming a smaller and smaller percentage of projects using NuGet. PackageReference doesn't have this issue, but PackageReference isn't supported by C++ projects.

**Comment by miraboreasumr** [comment]
> @miraboreasumr the most common cause of this problem is either changing the directory structure of projects, or adding a project to a second solution, where the relative path of that solution is different to the first solution the project correctly works in.
> 
> If you look at the project file in a text editor, you'll find the missing file referenced, and the relative path it expects the package to be in. You should also find a `packages` subdirectory in the directory that your `.sln` file is in. If they're not the same, the condition you see in your project file that reports the error, will report the error.
> 
> This can often be resolved by running `Update-Package -Reinstall` in the Package Manager Console. But as described above, if this project is in more than one solution, "fixing" it for one solution will break it for a different solution.
> 
> Since this is in the docs repo, I'm trying to think where this could be documented that will be easy to find. At the same time, this issue only exists for projects using packages.config, which is becoming a smaller and smaller percentage of projects using NuGet. PackageReference doesn't have this issue, but PackageReference isn't supported by C++ projects.

Thanks, I think I am not good enough to post an issue here, but I don't what exactly to operate to locate the problem.
Sorry for the bother, could you please tell me what I need to do to look at the project file in a text editor? So far, I just open the  .sln with Visual Studio in Windows, and include some dependencies. I didn't find the subfolder where the .sln is located. Thank you so much if you could help me!
