### ISSUE TITLE
Central Package Management example uses Update instead of Include

### ISSUE THREAD

**Issue by matt-entrekin** [NuGet/docs.microsoft.com-nuget#3222]
The Project1 xml code block on [the CPM doc page](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#central-package-management-rules) uses `<PackageVersion Update=` instead of `<PackageVersion Include=...`. 

```xml
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))" />
  <ItemGroup>
    <PackageVersion Update="Newtonsoft.Json" Version="12.0.1" />
  </ItemGroup>
</Project>
```

Using `Update` doesn't work and causes `nu1008` errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Version Independent ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Content: [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management)
* Content Source: [docs/consume-packages/Central-Package-Management.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by zivkan** [comment]
@matt-entrekin, the example isn't fully detailed, but it implies that a `PackageVersion` was already defined for the package in the imported Directory.Packages.props file from the `<Import` statement. This is how one subdirectory can use a different version of a package than a different subdirectory. If you were to use `Include`, rather than `Update`, then [you'd get a NU1506 warning about duplicate items for the same package](https://github.com/NuGet/NuGet.Client/blob/e520f969f09411cdbf024349cbae3a1f60c4c73c/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L262-L273)

**Comment by danlyons-softek** [comment]
@zivkan: how does that compare with using `VersionOverride`?

Is `Update` only intended for use in nested Directory.Package.props files, while `VersionOverride` is only for use in individual projects' csproj files?
