### ISSUE TITLE
`verify`:  Update documentation to indicate that `--certificate-fingerprint` only applies to a primary signature

### ISSUE THREAD

**Issue by dtivel** [NuGet/docs.microsoft.com-nuget#3279]
`verify` command's `--certificate-fingerprint` option only applies to a primary signature, not a primary signature timestamp, repository countersignature, or repository countersignature timestamp.  See [the code](https://github.com/NuGet/NuGet.Client/blob/7ad6fcc9c56c960975c37b2416c7eae1d53ba3fd/src/NuGet.Core/NuGet.Commands/VerifyCommand/VerifyCommandRunner.cs#L55-L61.

Docs for both NuGet.exe and dotnet nuget should be explicit about this.

**Comment by erdembayar** [comment]
So `dotnet nuget verify .\microsoft.analysisservices.netcore.retail.amd64.19.79.0.nupkg --certificate-fingerprint 1F4B311D9ACC115C8DC8018B5A49E00FCE6DA8E2855F9F014CA6F34570BC482D -v d` will fail, but `dotnet nuget verify .\microsoft.analysisservices.netcore.retail.amd64.19.79.0.nupkg --certificate-fingerprint 566A31882BE208BE4422F7CFD66ED09F5D4524A5994F50CCC8B05EC0528C1353 -v d` will succeed, because MS packages are signed with author and repository certificates and former one is primary signature for author signed package, not the repository signature.
