### ISSUE TITLE
Add information on NuGet repos

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#390]
Left nav should have ways to discover NuGet repos along with some information on what each repo is meant for. Additionally Report an issue link directly from here.

**Comment by kraigb** [comment]
Done. Added a TOC entry on the left side for GitHub repositories that goes to the NuGet Home page there. I did not add any content to the docs site, however, because it would be redundant with the GitHub page and thus create maintenance overhead to keep the pages in sync. Generally speaking, that page shows the most active repos already, so things like NuGet.Client and the docs repos are near the top.
