### ISSUE TITLE
We need docs for AssetTargetFallback, both generally and migrating from PackageTargetFallback .

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#511]
@Petermarcu commented on [Fri Oct 06 2017](https://github.com/NuGet/Home/issues/5998)

@richlander opened this here: https://github.com/dotnet/core/issues/725

We need docs for AssetTargetFallback, both generally and migrating from PackageTargetFallback .

---

@rrelyea commented on [Tue Oct 10 2017](https://github.com/NuGet/Home/issues/5998#issuecomment-335600096)

@karann-msft  - can you please help drive as necessary

**Comment by kraigb** [comment]
@nkolev92 Please provide references to where appropriate information can be found, or at least identify the subject matter expert who can provide the details.

**Comment by nkolev92** [comment]
Sure @kraigb 
I just migrated the issue, @emgarten implemented it so he should be able to provide some more details, ideally if he has some design docs stashed away.

**Comment by emgarten** [comment]
Here is an example

Project target framework: net46
Package contains:
* lib/netstandard1.3/a.dll
* build/net46/a.targets

In normal mode without these properties set the user will get only `build/net46/a.targets` as assets from this package since ns1.3 is not compatible.

With `PackageTargetFallback=netstandard1.6` the user will get `lib/netstandard1.3/a.dll` and `build/net46/a.targets` because NuGet finds the nearest compatible assets on a per folder basis. Selecting net46 from the build folder has no impact on the lib folder.

With `AssetTargetFallback=netstandard1.6` the user will get only `build/net46/a.targets`. Instead of making the decision independently nuget will instead check all folders, then if zero items were found (meaning the package is not compatible) it will then act as if the project target framework is netstandard1.6. In this scenario the build folder has assets so AssetTargetFallback is not used.

Both of these properties work as fallback project TFMs, they allow the project to select assets from a package using something different from the current project TFM.

PackageTargetFallback is deprecated and only AssetTargetFallback should be used.

netcoreapp2.0 projects have AssetTargetFallback=net461 by default in new projects.

**Comment by rrelyea** [comment]
My first attempt at this was here: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1264

**Comment by rrelyea** [comment]
My new outline:

Package Asset Selection
=========================

Pick most compatible assets (which TFM?)
If no compat assets, if ATF is set, try again with those.

example 1:
Project TFM is Net 472

Package contains Net460 and Net450
Answer: pick closest one net460

example 1b:
Project TFM is Net 472

Package contains Netstandard20 and net45
Answer: picks net45, cause it is same family

example 1c:
Project TFM is Net 472

Package contains Netstandard20 and netstandard 16
Answer: picks ns20, as it is more compat...see table..

example 2:
project tfm is netcoreapp 2.2

package contains netstandard 2.0 and netfx 461
answer: picks netstandard2.0

example 3:
project tfm is netstandard 2.0

package contains net461 and net40
answer: pick net461 (with NU1701 - we used ATF)





details on asset types
=======================

**Comment by nkolev92** [comment]
This should stay open :) We are still missing the docs :)
