### ISSUE TITLE
Improve documentation on use of runtimes folder and RIDs

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#600]
There are smatterings of info on this, but nothing that's particular clear on how and when to use it:

https://docs.microsoft.com/en-us/nuget/create-packages/project-json-and-uwp has the most, but seems limited to project.json.

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package mentions it in a table, but the link doesn't help any further.

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks mentions them.

https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages has various examples for native stuff.

Customer request on https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#comments-container:

> so, how is one supposed to use the \runtimes folder convention in conjunction with the \lib?
> 
> I have an assembly compiled as both x86 and x64, that needs to be on net452. Per the convention above of `{platform}-{architecture}\lib\{framework}`  I guess it I dont understand the platform vs architecture, as they are the same thing in msbuild, and I dont think you mean I should use  `x86-x86\lib\net452` 
> 
> If someone could point me to where I can find a list of "platforms" (not frameworks/tfm ) it would be appreciated.

**Comment by kraigb** [comment]
Related: https://github.com/NuGet/docs.microsoft.com-nuget/issues/592

**Comment by tpetrina** [comment]
Multi-targeting should definitively be explained better in docs.

**Comment by arlm** [comment]
Sorry but the actual behavior difference between .NET Framework 4.6.1, 4.7.2, .NET Core and .NET Standard are not documented on the issue of where to put libraries and which directories really are used in each case.

Seems that .NET Framework does not load `runtimes/{rid}/lib` directories but expects the managed assemblies to be all on either `ref/{tfm}` and/or `lib/{tfm}`.

The UWP document referenced on the first link of this issue states that pre-Windows 8 and post-Windows 8 behaviors also differ, but does using .NET Framework, .NET Standard or .NET Core affects or overrides this O.S. behavior? What about newer Windows Versions?

It would be best to have an official Microsoft statement on which is the expected behavior on each case or a table showing what to expect on each O.S. x .NET Framework/Runtime combination.
