### ISSUE TITLE
Long path problems

### ISSUE THREAD

**Issue by SQLEmil** [NuGet/docs.microsoft.com-nuget#942]
Why isn't the inability to restore with long file paths (https://github.com/NuGet/Home/issues/3324) listed as a known issue here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cc89bb8-e199-2108-5f45-db96988b4a15
* Version Independent ID: 44814abf-df30-97e8-da8a-ae4b98fda1ca
* Content: [Known Issues](https://docs.microsoft.com/en-us/nuget/release-notes/known-issues)
* Content Source: [docs/release-notes/Known-Issues.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/release-notes/Known-Issues.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
Thanks for asking @SQLEmil 

We now have our behavior fixed in nuget.exe and documented here (including notes on how different code paths work).
https://docs.microsoft.com/en-us/nuget/tools/cli-ref-long-path

Good start?
What else do you think is necessary?

Perhaps we document a note about it at the error message itself? Is there an error you receive when it fails that we can better document?
