### ISSUE TITLE
The latest version of NuGet package

### ISSUE THREAD

**Issue by kubakista** [NuGet/docs.microsoft.com-nuget#949]
"Without a version or version range, NuGet 2.8.x and earlier chooses the latest available package version when resolving a dependency, whereas NuGet 3.x and later chooses the lowest package version."

Is there any way how to specify "always latest" version regardless NuGet version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7db33-f188-0247-4c5e-035b25b11392
* Version Independent ID: 33cd8166-51d5-3ce3-8d6f-8f0df0310724
* Content: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/reference/package-versioning)
* Content Source: [docs/reference/Package-Versioning.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/Package-Versioning.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mizux** [comment]
@kubakista did you try simply `*` to enable [Floating (wildcard) Version](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#floating-wildcard-versions) ?

> When using the `PackageReference` format, NuGet also supports using a wildcard notation, *, for Major, Minor, Patch, and pre-release suffix parts of the number. Wildcards are not supported with the `packages.config` format.

src: https://docs.microsoft.com/en-us/nuget/reference/package-versioning#pre-release-versions

**Comment by iamwyza** [comment]
@Mizux - No this doesn't work.  Even if you do something like 
```xml
<PackageReference Include="My.Namespace.Thing" Version="2.0-*" />
```
and there is a 2.0.1-beta and a 2.0.97.6-beta, it will pick 2.0.1-beta instead of 2.0.97.6-beta.  That's completely useless to me.  If I'm using a wildcard its because I'm wanting to get the latest version, not the earliest. (earliest isn't going to change in a normal situation).

**Comment by derekrgoss** [comment]
@iamwyza - did you ever find a workaround for this?

**Comment by iamwyza** [comment]
Nope.  Just hard coding the value each time right now with a powershell
script.  Super frustrating and hacky, but it is what it is.

**Comment by tebeco** [comment]
Since lockfile do exists that would be lovelly to see WildCard working also for `major`.
Visual Studio `Package Manager` bug like hell with you do :

in a csproj :
`<PackageReference Include="xunit" Version="$XUnitPackageVersion)" />`

in an imported `packages.props` (with a `Directory.Build.props`) :
```
<Project>
  <PropertyGroup>
    <XUnitPackageVersion>2.*</XUnitPackageVersion>
  </PropertyGroup>
</Project>
```

`dotnet restore` will resolve `2.4.1` (today), but `Visual Studio Package Manager` will "see" `2.0.0`
Trying to do this would resolve to `0.0.0` (depending on local cache) :
```
<Project>
  <PropertyGroup>
    <XUnitPackageVersion>*</XUnitPackageVersion>
  </PropertyGroup>
</Project>
```

At least give us something like an MsBuild Property :
`<UnsafeAllowWildcardForMajor>true</UnsafeAllowWildcardForMajor>`
(with a better name probably).


Dangerous ? of course ! don't choose for us ...
Not dangerous in fact ... :
Lockfile ! that's why we asked for many years ...

Why ?
* add a lockfile
* resolve latest major only with lockfile support enabled

when/how would we use it ?
* on the CI in a separate build (no touching `master`)
* only resolve major to generate a lockfile
* check the build
* check the test
* spin the app / e2e
* the CI would bump the dependencies only if all ok
* push to `master`
* trigger master build / test / deploy to DevCi ...

This is what `dotnet-maestro` has been created
This why paket has so much success, t describe what "consumer want" and secure it

You are probably the best people, as the nuget team, to enlight users toward this guidance.
Please don't make choices for consumers

**Comment by iamwyza** [comment]
The irony is that according to the MCSD exam, the behavior of using * is supposed to select the latest version, not the earliest. :)

**Comment by karann-msft** [comment]
There currently isn't a way to specify always latest with package reference.

@kubakista - we already have an issue tracking this product feedback - https://github.com/NuGet/Home/issues/6697

I would ask that we continue the discussion on that issue since this is product feedback and the product team monitors the Home repo for feature asks and such. If you upvoted on this issue, consider doing so on the issue I linked above.

Thank you!
