### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by eschneider999** [NuGet/docs.microsoft.com-nuget#959]
What about the below items? :

_rels folder and .rels file
[Content_Types].xml (Why is this needed? seems redundant)
package folder & sub tree and file *.psmdcp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by mbedded** [comment]
You are talking about the nupkg-content, right? From my point of view this is not needed in this part of documentation because this is the inner structure of a package which is handled by NuGet-Server.

BTW: searching the internet for "content_types.xml" brought me to this interesting passage: Open Packaging Conventions. I was just scamming but it seems some of your questions are answered here.
https://en.wikipedia.org/wiki/Open_Packaging_Conventions

**Comment by karann-msft** [comment]
That's right. Those files are internal to how NuGet works and are intended to be transparent from a package authoring as well as consumption standpoint.

**Comment by Paul-Dempsey** [comment]
The phrase "...whose contents match certain conventions" is quite vague. It could be more specific and say something like: "whose contents follow the Open Packaging Conventions<link>, and other nuget layout conventions." No need to be coy about the package structure.
