### ISSUE TITLE
"Push and Delete" mentions API v3 but URLs use v2

### ISSUE THREAD

**Issue by Phrohdoh** [NuGet/docs.microsoft.com-nuget#964]
This article starts with the following copy:

> It is possible to push, delete (or unlist, depending on the server implementation), and relist packages using the NuGet V3 API. These operations are based off of the PackagePublish resource found in the service index.

But later uses the following url:

```
https://www.nuget.org/api/v2/package
```

Which is the v2 server API.

Is this a different between the "nuget v3 api" (which is the nuget client API?) and the server api (which, as said previously, is shown as v2)?

Or, does the copy reproduced above need to be changed to `NuGet V2 API`?

---

I do not know which is the correct change but I am happy to submit a PR with the proper fix if someone will point me in the right direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5691c1-f008-bbbf-a086-d9e665b5c332
* Version Independent ID: f255cc99-1041-ca5c-d2e5-5981e450a236
* Content: [Push and Delete, NuGet API](https://docs.microsoft.com/en-us/nuget/api/package-publish-resource)
* Content Source: [docs/api/package-publish-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/api/package-publish-resource.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by joelverhagen** [comment]
> But later uses the following url:
> 
> ```
> https://www.nuget.org/api/v2/package
> ```
> 
> Which is the v2 server API.

Theoretically, the fact that the string "v2" is in the V3 push URL should be irrelevant to the user or client implementation. The V3 service index is meant to simply provide URLs of any shape or pattern, associated with a `@type` string describing how the URL should be used. In other words, the URLs themselves should be opaque. This point is a bit of nitpick, but I wanted to state that first so you can better understand where I'm coming from.

Still a great question! Why do these "opaque" URLs happen to be the same between V3 push and V2 push?

The real reason the URL is the same is that the push, unlist/delete, and relist protocol did not change between the V2 and V3 protocol versions. The user scenarios around this endpoint have not changed for years so there was no need for a protocol change (small caveat: NuGet.org has relatively recent [additional requirements](https://docs.microsoft.com/en-us/nuget/api/nuget-protocols) on clients interacting with this endpoint).

> Is this a different between the "nuget v3 api" (which is the nuget client API?) and the server api (which, as said previously, is shown as v2)?

Because the protocol did not change, it was easiest for us to maintain a single endpoint used by both V2 and V3.

I would also like to point out that the V2 **feed** URL for NuGet.org is actually `https://www.nuget.org/api/v2` (no `package` suffix). In V2, there was the annoying separation between the feed URL and the push/delete URL. You can see this on MyGet and on NuGet.org. We did fix this up in V3 by referencing the push endpoint inside the V3 **feed** URL `https://api.nuget.org/v3/index.json` so that package authors and consumers can finally configure one feed URL into their client for all operations.

> Or, does the copy reproduced above need to be changed to NuGet V2 API?

I'm not sure what you mean. 

I hope this resolves your confusion. If not, I'd be happy to clear up any other questions you have.

**Comment by joelverhagen** [comment]
Oh, and sorry about the delay. I was out on paternity leave for 3 months so a whole bunch of GitHub notifications slipped through the cracks.
